USE DWH_COMFENALCO
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Eliminar restricciones de clave foránea
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'ALTER TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) 
    + ' DROP CONSTRAINT ' + QUOTENAME(f.name) + '; ' 
FROM sys.foreign_keys f
INNER JOIN sys.tables t ON f.parent_object_id = t.object_id
INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE s.name = 'Transversal';
EXEC sp_executesql @sql;
-- Eliminar tablas
SET @sql = '';
SELECT @sql += 'DROP TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) + '; ' 
FROM sys.tables t
INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE s.name = 'Transversal';
EXEC sp_executesql @sql;
-- Eliminar el esquema
IF EXISTS (SELECT * FROM sys.schemas WHERE name = 'Transversal')
BEGIN
    DROP SCHEMA Transversal;
END
GO
-- Crear el esquema Transversal
CREATE SCHEMA Transversal;
GO
-- Crear DIM_EMPRESAS
CREATE TABLE [Transversal].[DIM_EMPRESAS](
	[ID_EMPRESA] [int] NOT NULL,
	[PARTNER] [nvarchar](10) NOT NULL,
	[ID_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[COD_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[TIPO_DOCUMENTO] [nvarchar](40) NULL,
	[DOCUMENTO] [nvarchar](20) NULL,
	[RAZON_SOCIAL] [nvarchar](300) NULL,
	[ID_ESTADO] [nvarchar](2) NULL,
	[ESTADO] [nvarchar](40) NULL,
	[ID_SECTOR] [nvarchar](2) NULL,
	[SECTOR] [nvarchar](40) NULL,
	[ID_CLASE] [nvarchar](2) NULL,
	[CLASE] [nvarchar](40) NULL,
	[ID_ACT_ECONOMICA] [nvarchar](4) NULL,
	[ACT_ECONOMICA] [nvarchar](200) NULL,
	[ES_NUEVO] [int] NULL,
	[ID_TIPO_APORTANTE] [nvarchar](2) NULL,
	[TIPO_APORTANTE] [nvarchar](40) NULL,
	[FECHA_AFILIACION] [datetime] NULL,
	[FECHA_FUNDACION] [nvarchar](50) NULL,
	[FECHA_RETIRO] [nvarchar](50) NULL,
	[ID_MOTIVO_RETIRO] [int] NULL,
	[MOTIVO_RETIRO] [nvarchar](80) NULL,
	[FECHA_DESDE] [datetime] NULL,
	[FECHA_HASTA] [datetime] NULL,
	[DIRECCION] [nvarchar](300) NULL,
	[TELEFONO] [nvarchar](30) NULL,
	[COD_CIUDAD] [nvarchar](5) NULL,
	[NUMERO_PROCESO_SQL] [bigint] NULL,
	[FEC_CREACION] [datetime] NULL,
	[USUARIO_PROCESO] [varchar](50) NULL,
	[FEC_ACTUALIZACION] [datetime] NULL,
	[ESTADOREGISTRO] [nvarchar](10) NULL,
	[CORREO] [nvarchar](200) NULL,
	[TIPO_PERSONA] [nvarchar](1) NULL,
	[PRIMER_NOMBRE] [nvarchar](50) NULL,
	[SEGUNDO_NOMBRE] [nvarchar](50) NULL,
	[PRIMER_APELLIDO] [nvarchar](50) NULL,
	[SEGUNDO_APELLIDO] [nvarchar](50) NULL,
	[CONVENIO_LIB] [int] NULL,
	[FECHA_PRIMER_APORTE] [int] NULL,
	[DIGITO_VERIFICACON] [varchar](1) NULL,
	[CAJA_COMPEN] [varchar](2) NULL,
	[SITUACION_1429] [nvarchar](10) NULL,
	[PROGRESIVIDAD_1429] [nvarchar](10) NULL,
	[SITUACION_590] [nvarchar](10) NULL,
	[PROGRESIVIDAD_590] [nvarchar](10) NULL,
	[ORIGEN_EXTRACCION] [varchar](50) NULL,
	CONSTRAINT [PK_DIM_EMPRESAS] PRIMARY KEY CLUSTERED ([ID_EMPRESA])
) ON [PRIMARY]
GO
-- Crear DIM_AFILIADOS
CREATE TABLE [Transversal].[DIM_AFILIADOS](
	[ID_AFILIADO] [int] NOT NULL,
	[PARTNER] [nvarchar](10) NOT NULL,
	[ID_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[COD_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[TIPO_DOCUMENTO] [nvarchar](40) NULL,
	[NUMERO_DOCUMENTO] [nvarchar](20) NULL,
	[NOMBRE_COMPLETO] [nvarchar](200) NULL,
	[PRIMER_APELLIDO] [nvarchar](50) NULL,
	[SEGUNDO_APELLIDO] [nvarchar](50) NULL,
	[PRIMER_NOMBRE] [nvarchar](50) NULL,
	[SEGUNDO_NOMBRE] [nvarchar](50) NULL,
	[ID_TIPO_AFILIADO] [nvarchar](2) NULL,
	[TIPO_AFILIADO] [varchar](80) NULL,
	[ID_CATEGORIA] [nvarchar](2) NULL,
	[CATEGORIA] [nvarchar](10) NULL,
	[ID_ESTADO_AFILIACION] [nvarchar](4) NULL,
	[ESTADO_AFILIACION] [nvarchar](40) NULL,
	[FECHA_AFILIACION] [nvarchar](50) NULL,
	[FECHA_RETIRO] [nvarchar](50) NULL,
	[ID_MOTIVORETIRO] [nvarchar](2) NULL,
	[MOTIVORETIRO] [nvarchar](50) NULL,
	[ID_NIVEL_EDUCATIVO] [nvarchar](2) NULL,
	[NIVEL_EDUCATIVO] [varchar](50) NULL,
	[ID_GENERO] [nvarchar](2) NULL,
	[GENERO] [varchar](20) NULL,
	[ID_ORIENTACION_SEXUAL] [nvarchar](2) NULL,
	[ORIENTACION_SEXUAL] [nvarchar](40) NULL,
	[ID_ESTADO_CIVIL] [nvarchar](2) NULL,
	[ESTADO_CIVIL] [nvarchar](40) NULL,
	[COD_OCUPACION] [nvarchar](4) NULL,
	[OCUPACION] [nvarchar](100) NULL,
	[ID_PERTENENCIA_ETNICA] [nvarchar](2) NULL,
	[PERTENENCIA_ETNICA] [nvarchar](100) NULL,
	[ID_FACTOR_VULNERABILIDAD] [nvarchar](2) NULL,
	[FACTOR_VULNERABILIDAD] [nvarchar](50) NULL,
	[CONDICION_ESPECIAL] [nvarchar](2) NULL,
	[FECHA_NACIMIENTO] [nvarchar](10) NULL,
	[DIRECCION] [nvarchar](60) NULL,
	[TELEFONO] [nvarchar](30) NULL,
	[BARRIO] [nvarchar](40) NULL,
	[ESTRATO] [nvarchar](2) NULL,
	[ID_CIUDAD] [nvarchar](5) NULL,
	[ID_AREA_GEOGRAFICA] [nvarchar](2) NULL,
	[AREA_GEOGRAFICA] [nvarchar](10) NULL,
	[CORREO] [nvarchar](250) NULL,
	[SALARIO_BASICO] [nvarchar](50) NULL,
	[ES_NUEVO] [nvarchar](50) NULL,
	[TIPO_SALARIO] [nvarchar](50) NULL,
	[HORAS_LAB_MENSUAL] [nvarchar](50) NULL,
	[TIPO_APORTANTE] [nvarchar](50) NOT NULL,
	[APORTANTE] [nvarchar](10) NULL,
	[FEC_DESDE] [datetime] NULL,
	[FEC_HASTA] [datetime] NULL,
	[FEC_CREACION] [datetime] NULL,
	[FEC_ACTUALIZACION] [datetime] NULL,
	[USUARIO_PROCESO] [varchar](50) NULL,
	[ESTADOREGISTRO] [nvarchar](20) NULL,
	[ID_RESGUARDO] [int] NULL,
	[RESGUARDO] [varchar](100) NULL,
	[COD_PAIS_RESIDENCIA] [int] NULL,
	[PAIS_RESIDENCIA] [varchar](100) NULL,
	[COD_MUN_LABOR_DANE] [varchar](5) NULL,
	[AREA_GEOGRA_LABOR] [varchar](2) NULL,
	[FECHA_INGRESO_EMPRESA] [varchar](50) NULL,
	[ID_EMPRESA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
	[EMPRESA_PRINCIPAL] [varchar](1) NULL,
	[VALOR_SALARIO_UVT] [numeric](18, 2) NULL,
	[ID_CATEGORIA_UVT] [varchar](2) NULL,
	[CATEGORIA_UVT] [varchar](10) NULL,
 CONSTRAINT [PK_DIM_AFILIADOS] PRIMARY KEY CLUSTERED 
(
	[ID_AFILIADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
CONSTRAINT [FK_DIM_AFILIADOS_DIM_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [Transversal].[DIM_EMPRESAS]([ID_EMPRESA])
) ON [PRIMARY]
GO
-- Crear DIM_BENEFICIARIOS
CREATE TABLE [Transversal].[DIM_BENEFICIARIOS](
	[ID_BENEFICIARIO] [int] NOT NULL,
	[PARTNER] [nvarchar](10) NOT NULL,
	[TITULAR] [nvarchar](10) NOT NULL,
	[ID_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[COD_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[TIPO_DOCUMENTO] [nvarchar](40) NULL,
	[NUMERO_DOCUMENTO] [nvarchar](20) NULL,
	[NOMBRE_COMPLETO] [nvarchar](81) NULL,
	[PRIMER_APELLIDO] [nvarchar](40) NOT NULL,
	[SEGUNDO_APELLIDO] [nvarchar](40) NULL,
	[PRIMER_NOMBRE] [nvarchar](40) NOT NULL,
	[SEGUNDO_NOMBRE] [nvarchar](40) NULL,
	[ID_PARENTESCO] [nvarchar](8) NULL,
	[PARENTESCO] [varchar](50) NULL,
	[FECHA_AFILIACION] [nvarchar](50) NOT NULL,
	[FECHA_RETIRO] [nvarchar](50) NULL,
	[ID_GENERO] [varchar](1) NOT NULL,
	[GENERO] [varchar](9) NOT NULL,
	[ID_NIVEL_EDUCATIVO] [nvarchar](2) NULL,
	[NIVEL_EDUCATIVO] [nvarchar](50) NULL,
	[ID_ESTADO_CIVIL] [nvarchar](2) NULL,
	[ESTADO_CIVIL] [nvarchar](40) NULL,
	[DISCAPACIDAD] [nvarchar](1) NULL,
	[FECHA_NACIMIENTO] [datetime] NOT NULL,
	[DIRECCION] [nvarchar](60) NULL,
	[TELEFONO] [nvarchar](30) NULL,
	[BARRIO] [nvarchar](40) NULL,
	[ESTRATO] [nvarchar](2) NULL,
	[ID_CIUDAD] [nvarchar](5) NULL,
	[ID_AREA_GEOGRAFICA] [nvarchar](2) NULL,
	[AREA_GEOGRAFICA] [nvarchar](10) NULL,
	[FEC_CREACION] [datetime] NULL,
	[USUARIO_PROCESO] [varchar](40) NULL,
	[FEC_ACTUALIZACION] [datetime] NULL,
	[ESTADOREGISTRO] [nvarchar](10) NULL,
	[ID_PARENT_SAP] [nvarchar](10) NULL,
	[PARENT_SAP] [nvarchar](30) NULL,
	[ID_AFILIADO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
	[APORTANTE] [nvarchar](10) NULL,
	[TIPO_AFILIADO] [nvarchar](50) NOT NULL,
	[TIPO_APORTANTE] [nvarchar](50) NOT NULL,
	[FEC_DESDE] [datetime] NULL,
	[FEC_HASTA] [datetime] NULL,
	[ESTADO_BEN] [int] NULL,
	[FECHA_INGRESO_EMPRESA] [varchar](50) NULL,
 CONSTRAINT [PK_DIM_BENENEFICIARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_BENEFICIARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
CONSTRAINT [FK_DIM_BENEFICIARIOS_DIM_AFILIADOS] FOREIGN KEY ([ID_AFILIADO]) REFERENCES [Transversal].[DIM_AFILIADOS]([ID_AFILIADO])
) ON [PRIMARY]
GO
-- Crear DIM_APORTANTE_NOAFILIADO
CREATE TABLE [Transversal].[DIM_APORTANTE_NOAFILIADO](
	[ID_APORTANTE] [int] NOT NULL,
	[PARTNER] [nvarchar](10) NOT NULL,
	[ID_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[COD_TIPO_DOCUMENTO] [nvarchar](4) NULL,
	[TIPO_DOCUMENTO] [nvarchar](40) NULL,
	[DOCUMENTO] [nvarchar](20) NULL,
	[RAZON_SOCIAL] [nvarchar](300) NULL,
	[ID_ESTADO] [nvarchar](2) NULL,
	[ESTADO] [nvarchar](40) NULL,
	[ID_SECTOR] [nvarchar](2) NULL,
	[SECTOR] [nvarchar](40) NULL,
	[ID_CLASE] [nvarchar](2) NULL,
	[CLASE] [nvarchar](40) NULL,
	[ID_ACT_ECONOMICA] [nvarchar](4) NULL,
	[ACT_ECONOMICA] [nvarchar](200) NULL,
	[ES_NUEVO] [int] NULL,
	[ID_TIPO_APORTANTE] [nvarchar](2) NULL,
	[TIPO_APORTANTE] [nvarchar](40) NULL,
	[FECHA_AFILIACION] [datetime] NULL,
	[FECHA_FUNDACION] [nvarchar](50) NULL,
	[FECHA_RETIRO] [nvarchar](50) NULL,
	[ID_MOTIVO_RETIRO] [int] NULL,
	[MOTIVO_RETIRO] [nvarchar](80) NULL,
	[FECHA_DESDE] [datetime] NULL,
	[FECHA_HASTA] [datetime] NULL,
	[DIRECCION] [nvarchar](300) NULL,
	[TELEFONO] [nvarchar](30) NULL,
	[COD_CIUDAD] [nvarchar](5) NULL,
	[NUMERO_PROCESO_SQL] [bigint] NULL,
	[FEC_CREACION] [datetime] NULL,
	[USUARIO_PROCESO] [varchar](50) NULL,
	[FEC_ACTUALIZACION] [datetime] NULL,
	[ESTADOREGISTRO] [nvarchar](10) NULL,
	[CORREO] [nvarchar](200) NULL,
	[TIPO_PERSONA] [nvarchar](1) NULL,
	[PRIMER_NOMBRE] [nvarchar](50) NULL,
	[SEGUNDO_NOMBRE] [nvarchar](50) NULL,
	[PRIMER_APELLIDO] [nvarchar](50) NULL,
	[SEGUNDO_APELLIDO] [nvarchar](50) NULL,
	[CONVENIO_LIB] [int] NULL,
	[FECHA_PRIMER_APORTE] [int] NULL,
	[DIGITO_VERIFICACON] [varchar](1) NULL,
	[CAJA_COMPEN] [varchar](2) NULL,
	[SITUACION_1429] [nvarchar](10) NULL,
	[PROGRESIVIDAD_1429] [nvarchar](10) NULL,
	[SITUACION_590] [nvarchar](10) NULL,
	[PROGRESIVIDAD_590] [nvarchar](10) NULL,
	[FECHA_NACIMIENTO] [varchar](8) NULL,
	[GENERO] [int] NULL,
	CONSTRAINT [PK_DIM_APORTANTE_NOAFILIADO] PRIMARY KEY CLUSTERED ([ID_APORTANTE])
) ON [PRIMARY]
GO
-- Crear FACT_APORTES_SHR_DET
CREATE TABLE [Transversal].[FACT_APORTES_SHR_DET](
	[ID_EMPRESA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
	[ID_AFILIADO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
	[PERIODO] [varchar](10) NULL,
	[ID_FECHA] [int] NULL DEFAULT 20090101, -- Asignar valor por defecto de 1 de enero de 2009,
	[OPBEL] [varchar](50) NULL,
	[BELNR] [varchar](50) NULL,
	[MOVIMIENTO] [varchar](50) NULL,
	[FECHA_CONTABLE] [int] NULL,
	[NUM_CUENTA] [varchar](50) NULL,
	[APORTE] [varchar](50) NULL,
	[INTERES] [varchar](50) NULL,
	[ESTADOREGISTRO] [varchar](50) NULL,
	[FECHA_ACTUALIZACION] [datetime] NULL,
	[DESDE] [datetime] NULL,
	[HASTA] [datetime] NULL,
	[PROCESO] [nvarchar](50) NULL,
	[BP_EMPRESA] [varchar](10) NULL,
	[BP_AFILIADO] [varchar](10) NULL,
	[TIPO_APORTANTE] [int] NULL,
	[SW_AJUSTE] [int] NULL,
	[APORTE_NUEVO] [numeric](18, 0) NULL,
	CONSTRAINT [FK_FACT_APORTES_SHR_DET_DIM_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [Transversal].[DIM_EMPRESAS]([ID_EMPRESA]),
	CONSTRAINT [FK_FACT_APORTES_SHR_DET_DIM_AFILIADOS] FOREIGN KEY ([ID_AFILIADO]) REFERENCES [Transversal].[DIM_AFILIADOS]([ID_AFILIADO]),
	CONSTRAINT [FK_FACT_APORTES_SHR_DET_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
) ON [PRIMARY]
GO
ALTER TABLE [Transversal].[FACT_APORTES_SHR_DET] ADD  DEFAULT ((0)) FOR [SW_AJUSTE]
GO
ALTER TABLE [Transversal].[FACT_APORTES_SHR_DET] ADD  DEFAULT ((0)) FOR [APORTE_NUEVO]
GO
CREATE TABLE [Transversal].[DIM_CUENTA_CONTABLE](
	[ID_CUENTA] [bigint] IDENTITY(1,1) NOT NULL,
	[CUENTA_NUMERO] [bigint] NOT NULL,
	[CUENTA] [nvarchar](10) NOT NULL,
	[CUENTA_HOMOLOGA] [nvarchar](10) NOT NULL,
	[DESCRIPCION] [nvarchar](50) NOT NULL,
	[TIPO_CUENTA] [nvarchar](100) NOT NULL,
	[TIPO_OPERACION] [nvarchar](100) NOT NULL,
	[GRUPO_CUENTA] [nvarchar](100) NOT NULL,
	[SUBGRUPO_CUENTA] [nvarchar](50) NOT NULL,
	[GRUPO_OPERACION] [nvarchar](100) NOT NULL,
	[FEC_PROCESO] [datetime] NOT NULL,
	[UDATE] [datetime] NOT NULL,
	[CUENTA_SSF] [int] NOT NULL,
	[DESCRIPCION_SSF] [nvarchar](255) NOT NULL,
	[CUENTA_DESCRIPCION]  AS (([CUENTA]+'-')+[DESCRIPCION]),
	[CUENTA_DESCRIPCION_SSF]  AS ((rtrim(CONVERT([varchar],[CUENTA_SSF]))+'-')+[DESCRIPCION_SSF]),
	[SIGNO_INGRESOS]  AS (case when [TIPO_CUENTA]='INGRESOS' then (1) else (0) end),
	[NUMERO_PROCESO_SQL] [bigint] NOT NULL,
	[CLASIFICACION] [int] NULL,
	[USUARIO_PROCESO] [nvarchar](50) NOT NULL,
	[ESTADO_REGISTRO] [nvarchar](10) NULL,
	[NIVEL_1_TIPO_CUENTA]  AS (left(CONVERT([varchar](20),[CUENTA_NUMERO]),(1))),
	[DESC_NIVEL_1_TIPO_CUENTA]  AS ([TIPO_CUENTA]),
	[NIVEL_2_TIPO_OPERAC]  AS (left(CONVERT([varchar](20),[CUENTA_NUMERO]),(2))),
	[DES_NIVEL_2_TIPO_OPERAC]  AS ([TIPO_OPERACION]),
	[NIVEL_4_GRUPO_CTA]  AS (left(CONVERT([varchar](20),[CUENTA_NUMERO]),(4))),
	[DESC_NIVEL_4_GRUPO_CTA]  AS ([GRUPO_CUENTA]),
	[NIVEL_6_SUBG_CTA]  AS (left(CONVERT([varchar](20),[CUENTA_NUMERO]),(6))),
	[DESC_NIVEL_6_SUBG_CTA]  AS ([SUBGRUPO_CUENTA]),
	[NIVEL_8_GRUPO_OPERAC]  AS (left(CONVERT([varchar](20),[CUENTA_NUMERO]),(8))),
	[DESC_NIVEL_8_GRUPO_OPERAC]  AS ([GRUPO_OPERACION]),
	[NIVEL_10_CUENTA]  AS (left(CONVERT([varchar](20),[CUENTA_NUMERO]),(10))),
	[DESC_NIVEL_10_CUENTA_NUMERO]  AS ([DESCRIPCION]),
	[ID_CUENTA_AUXILIAR] AS ([ID_CUENTA]),
 CONSTRAINT [PK_DIM_CUENTA_CONTABLE] PRIMARY KEY CLUSTERED 
(
	[ID_CUENTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
-- Crear DIM_UNIDAD
 CREATE TABLE [Transversal].[DIM_UNIDAD] (
    [ID_UNIDAD] [int] IDENTITY(1,1) NOT NULL,
    [UNIDAD] [nvarchar](40),
	CONSTRAINT [PK_DIM_UNIDAD] PRIMARY KEY CLUSTERED ([ID_UNIDAD])
)
GO
-- Crear DIM_UNIDADES_ORGANIZATIVAS
CREATE TABLE [Transversal].[DIM_UNIDADES_ORGANIZATIVAS](
	[ID_CEBE] [bigint] NOT NULL,
	[CEBE] [varchar](10) NOT NULL,
	[DESCRIPCION_BREVE] [varchar](50) NOT NULL,
	[DESCRIPCION_COMPLETA] [varchar](100) NOT NULL,
	[CEBE_DESCRIPCION]  AS ((rtrim(CONVERT([char],[CEBE]))+'-')+[DESCRIPCION_COMPLETA]),
	[DEPARTAMENTO] [varchar](100) NOT NULL,
	[AREA] [varchar](100) NOT NULL,
	[SUBAREA] [varchar](100) NOT NULL,
	[SEGMENTO] [bigint] NOT NULL,
	[DESCRIPCION_SEGMENTO] [varchar](50) NOT NULL,
	[SEGMENTO_DESCRIPCION]  AS ((rtrim(CONVERT([char],[SEGMENTO]))+'-')+[DESCRIPCION_SEGMENTO]),
	[CODIGO_SSF] [int] NOT NULL,
	[NOMBRE_SSF] [varchar](100) NOT NULL,
	[CODIGO_NOMBRE_SSF]  AS ((rtrim(CONVERT([char],[CODIGO_SSF]))+'-')+[NOMBRE_SSF]),
	[UDATE] [smalldatetime] NOT NULL,
	[NUMERO_PROCESO_SQL] [bigint] NOT NULL,
	[FEC_PROCESO] [datetime] NULL,
	[USUARIO_PROCESO] [varchar](50) NULL,
	[GRUPO_CEBE] [varchar](50) NULL,
	[ID_UNIDAD] [int] NOT NULL,
 CONSTRAINT [PK__DIM_UNIDADES_ORGANIZATIVAS] PRIMARY KEY CLUSTERED 
(
	[ID_CEBE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Transversal].[DIM_UNIDADES_ORGANIZATIVAS]  WITH NOCHECK ADD  CONSTRAINT [FK_DIM_UNIDADES_ORGANIZATIVAS_DIM_UNIDAD] FOREIGN KEY([ID_UNIDAD])
REFERENCES [Transversal].[DIM_UNIDAD] ([ID_UNIDAD])
GO
-- FACT_DETALLE_CONTABLE
CREATE TABLE [Transversal].[FACT_DETALLE_CONTABLE](
	[ID_CEBE] [bigint] NOT NULL,
	[ID_CUENTA] [bigint] NOT NULL,
	[ID_FECHA] [int] NOT NULL,
	[SEGMENT] [bigint] NOT NULL,
	[IMPORTE] [decimal](28, 2),-- NOT NULL,
	[INGRESOS] [decimal](28, 2) ,--NOT NULL,
	[INGRESOS_OPERACIONALES] [decimal](28, 2),-- NOT NULL,
	[GASTOS] [decimal](28, 2) ,--NOT NULL,
	[GASTOS_OPERACIONALES] [decimal](28, 2),-- NOT NULL,
	[GASTOS_OPERACIONALES_ADMIN] [decimal](28, 2),-- NOT NULL,
	[RESULTADO_EJERCICIO] [decimal](28, 2),-- NOT NULL,
	[COSTOS] [decimal](28, 2),-- NOT NULL,
	[ACTIVO] [decimal](28, 2),-- NOT NULL,
	[PASIVO] [decimal](28, 2),-- NOT NULL,
	[PATRIMONIO] [decimal](28, 2),-- NOT NULL,
	[GASTOS_CON_DISTRIBUCION] [decimal](28, 2),-- NOT NULL,
	[GASTOS_SIN_DISTRIBUCION] [decimal](28, 2),-- NOT NULL,
	[FECHA_REGISTRO_SAP] [datetime] NOT NULL,
	[FECHA_PROCESO] [datetime] NOT NULL,
	[USUARIO_PROCESO] [varchar](50) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [Transversal].[FACT_DETALLE_CONTABLE]  WITH NOCHECK ADD  CONSTRAINT [FK_FACT_DETALLE_CONTABLE_DIM_CUENTA_CONTABLE] FOREIGN KEY([ID_CUENTA])
REFERENCES [Transversal].[DIM_CUENTA_CONTABLE] ([ID_CUENTA])
GO

ALTER TABLE [Transversal].[FACT_DETALLE_CONTABLE] CHECK CONSTRAINT [FK_FACT_DETALLE_CONTABLE_DIM_CUENTA_CONTABLE]
GO

ALTER TABLE [Transversal].[FACT_DETALLE_CONTABLE]  WITH NOCHECK ADD  CONSTRAINT [FK_FACT_DETALLE_CONTABLE_Dim_TIEMPO] FOREIGN KEY([ID_FECHA])
REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
GO

ALTER TABLE [Transversal].[FACT_DETALLE_CONTABLE] CHECK CONSTRAINT [FK_FACT_DETALLE_CONTABLE_Dim_TIEMPO]
GO

ALTER TABLE [Transversal].[FACT_DETALLE_CONTABLE]  WITH NOCHECK ADD  CONSTRAINT [FK_FACT_DETALLE_CONTABLE_DIM_UNIDADES_ORGANIZATIVAS] FOREIGN KEY([ID_CEBE])
REFERENCES [Transversal].[DIM_UNIDADES_ORGANIZATIVAS] ([ID_CEBE])
GO

ALTER TABLE [Transversal].[FACT_DETALLE_CONTABLE] CHECK CONSTRAINT [FK_FACT_DETALLE_CONTABLE_DIM_UNIDADES_ORGANIZATIVAS]
GO

-- Crear FACT_PRESUPUESTO
CREATE TABLE [Transversal].[FACT_PRESUPUESTO](
	[ID_CEBE] [bigint] NOT NULL,
	[ID_CUENTA] [bigint] NOT NULL,
	[ID_FECHA] [int] NOT NULL,
	[ID_TIPO_PRESUPUESTO] [int] NOT NULL,
	[SEGMENT] [bigint] NOT NULL,
	[VALOR] [decimal](28, 2) NOT NULL,
	[INGRESOS] [decimal](28, 2) NOT NULL,
	[INGRESOS_OPERACIONALES] [decimal](28, 2) NOT NULL,
	[GASTOS] [decimal](28, 2) NOT NULL,
	[GASTOS_OPERACIONALES] [decimal](28, 2) NOT NULL,
	[GASTOS_OPERACIONALES_ADMIN] [decimal](28, 2) NOT NULL,
	[COSTOS] [decimal](28, 2) NOT NULL,
	[GASTOS_CON_DISTRIBUCION] [decimal](28, 2) NOT NULL,
	[GASTOS_SIN_DISTRIBUCION] [decimal](28, 2) NOT NULL,
	[FECHA_PROCESO] [datetime] NOT NULL,
	[USUARIO_PROCESO] [varchar](50) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [Transversal].[FACT_PRESUPUESTO]  WITH NOCHECK ADD  CONSTRAINT [FK_FACT_PRESUPUESTO_DIM_CUENTA_CONTABLE] FOREIGN KEY([ID_CUENTA])
REFERENCES [Transversal].[DIM_CUENTA_CONTABLE] ([ID_CUENTA])
GO

ALTER TABLE [Transversal].[FACT_PRESUPUESTO] CHECK CONSTRAINT [FK_FACT_PRESUPUESTO_DIM_CUENTA_CONTABLE]
GO

ALTER TABLE [Transversal].[FACT_PRESUPUESTO]  WITH NOCHECK ADD  CONSTRAINT [FK_FACT_PRESUPUESTO_Dim_TIEMPO] FOREIGN KEY([ID_FECHA])
REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
GO

ALTER TABLE [Transversal].[FACT_PRESUPUESTO] CHECK CONSTRAINT [FK_FACT_PRESUPUESTO_Dim_TIEMPO]
GO


ALTER TABLE [Transversal].[FACT_PRESUPUESTO]  WITH NOCHECK ADD  CONSTRAINT [FK_FACT_PRESUPUESTO_DIM_UNIDADES_ORGANIZATIVAS] FOREIGN KEY([ID_CEBE])
REFERENCES [Transversal].[DIM_UNIDADES_ORGANIZATIVAS] ([ID_CEBE])
GO

ALTER TABLE [Transversal].[FACT_PRESUPUESTO] CHECK CONSTRAINT [FK_FACT_PRESUPUESTO_DIM_UNIDADES_ORGANIZATIVAS]
GO

-- Crear DIM_SERVICIOS
 /*CREATE TABLE [Transversal].[DIM_SERVICIOS] (
    [ID_SERVICIO] [int] IDENTITY(1,1) NOT NULL,
    [SERVICIO] [nvarchar](40) NOT NULL,
	[ID_UNIDAD] [int]  NOT NULL,
    [CON_OBJETO_TARIFA] [nvarchar](40) NOT NULL,
    [VAL_TARIFA] [decimal](28, 2) NOT NULL,
    [COD_CATEGORIA] [nvarchar](40) NOT NULL,
    [CATEGORIA] [nvarchar](40) NOT NULL,
    [LINEA_INTERVENCION] [nvarchar](40),
    [CUPOS_DISPONIBLES] [int] NOT NULL,
    [ANIO_TARIFA] [varchar](10) NOT NULL,
    [CIUDAD] [nvarchar](40) NOT NULL,
    [ID_ESTABLECIMIENTO] [nvarchar](40) NOT NULL,
    [NOMBRE_ESTABLECIMIENTO] [nvarchar](40) NOT NULL,
    [SEDE_ESTABLECIMIENTO] [nvarchar](40) NOT NULL,
    [COD_INFRAESTRUCTURA_CCF] [nvarchar](40) NOT NULL,
	CONSTRAINT [PK_DIM_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_SERVICIO]),
	CONSTRAINT [FK_DIM_SERVICIOS_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD])
)
GO*/

-- Crear DIM_INFRAESTRUCTURA_CCF
 CREATE TABLE [Transversal].[DIM_INFRAESTRUCTURA_CCF] (
    [COD_INFRAESTRUCTURA_CCF] [nvarchar](40) NOT NULL,
	[DESCRIPCION] [nvarchar](40) NOT NULL,
	[ID_UNIDAD] [int] NULL DEFAULT 5, -- Asignar valor por defecto de 5,
	CONSTRAINT [PK_DIM_INFRAESTRUCTURA_CCF] PRIMARY KEY CLUSTERED ([COD_INFRAESTRUCTURA_CCF]),
	CONSTRAINT [FK_COD_INFRAESTRUCTURA_CCF_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD])
)
GO
-- Crear DIM_CATEGORIA
 CREATE TABLE [Transversal].[DIM_CATEGORIA] (
    [COD_CATEGORIA] [nvarchar](40) NOT NULL,
	[DESCRIPCION] [nvarchar](40) NOT NULL,
	CONSTRAINT [PK_DIM_CATEGORIA] PRIMARY KEY CLUSTERED ([COD_CATEGORIA])
)
GO

-- Crear DIM_TARIFA_SERVICIOS
 CREATE TABLE [Transversal].[DIM_TARIFAS_SERVICIOS] (
    [ID_TARIFA] [int] IDENTITY(1,1) NOT NULL,
	[COD_SERVICIO] [int] NOT NULL,
    [CON_OBJETO_TARIFA] [nvarchar](255) NOT NULL,
	[COS_UNITARIO_CONCEPTO] [decimal](28, 2) NOT NULL,
    [VAL_TARIFA] [decimal](28, 2) NOT NULL,
    [COD_CATEGORIA] [nvarchar](40) NULL DEFAULT 3, -- Asignar valor por defecto de 3 categoria C,
    [ANIO_TARIFA] [varchar](10) NOT NULL,
    [COD_INFRAESTRUCTURA_CCF] [nvarchar](40) NOT NULL,
	[ID_TARIFA_AUXILIAR] AS ( [ANIO_TARIFA] + '_' + [COD_INFRAESTRUCTURA_CCF] + '_' + CAST([COD_SERVICIO] AS NVARCHAR(10)) + '_' + [COD_CATEGORIA] ) PERSISTED,
	CONSTRAINT [PK_DIM_TARIFA_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_TARIFA]),
	CONSTRAINT [FK_DIM_TARIFA_SERVICIOS_DIM_CATEGORIA] FOREIGN KEY ([COD_CATEGORIA]) REFERENCES [Transversal].[DIM_CATEGORIA]([COD_CATEGORIA]),
	CONSTRAINT [FK_DIM_TARIFA_SERVICIOS_DIM_INFRAESTRUCTURA_CCF] FOREIGN KEY ([COD_INFRAESTRUCTURA_CCF]) REFERENCES [Transversal].[DIM_INFRAESTRUCTURA_CCF]([COD_INFRAESTRUCTURA_CCF])
)
GO

-- Crear DIM_PERSONAL
 CREATE TABLE [Transversal].[DIM_PERSONAL] (
    [ID_PERSONAL] [int] IDENTITY(1,1) NOT NULL,
	[COD_PERSONA_UNIDAD] [nvarchar](40),
    [ID_UNIDAD] [int] NULL DEFAULT 5, -- Asignar valor por defecto de 5,
    [SERVICIO] [nvarchar](255),
	[NOMBRE] [nvarchar](255),
    [TELEFONO] [nvarchar](40),
    [CELULAR] [nvarchar](40),
    [CORREO] [nvarchar](255),
    [DIRECCION] [nvarchar](300),
    [CIUDAD] [nvarchar](255),
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
    [DOCUMENTO] [nvarchar](20) NOT NULL,
    [FECHA_NACIMIENTO] [datetime],
    [GENERO] [nvarchar](40),
    [HORAS_CONTRATADAS_MENSUAL] [decimal](18, 2) ,
    [HORAS_CONTRATADAS_TOTALES] [decimal](18, 2) ,
    [VALOR_TOTAL] [decimal](18, 2) ,
    [TIPO_CONTRATACION] [nvarchar](40),
    [FECHA_INICIO_CONTRATACION] [datetime],
    [FECHA_FIN_CONTRATACION] [datetime],
    [CAUSA_TERMINACION_CONTRATO] [nvarchar](40),
    [PREGRADO] [nvarchar](255),
    [POSGRADO_ESPECIALIDAD] [nvarchar](255),
    [POSGRADO_MAESTRIA] [nvarchar](255),
    [POSGRADO_DOCTORADO] [nvarchar](255),
    [NIVEL_INGLES] [nvarchar](40),
    [AREA] [nvarchar](255),
	CONSTRAINT [PK_DIM_PERSONAL] PRIMARY KEY CLUSTERED ([ID_PERSONAL]),
	CONSTRAINT [FK_DIM_PERSONAL_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD])
)
GO
-- Crear FACT_ENCUESTAS
 CREATE TABLE [Transversal].[FACT_ENCUESTAS] (
	[ID_ENCUESTA] [int] IDENTITY(1,1) NOT NULL,
	[ID_FECHA] [int] NULL DEFAULT 20090101, -- Asignar valor por defecto de 1 de enero de 2009,
    [FECHA_ENCUESTA] [datetime] NOT NULL,
    [ID_UNIDAD] [int] NULL DEFAULT 5, -- Asignar valor por defecto de 5
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
	[DOCUMENTO] [nvarchar](40),
	[ID_EMPRESA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_AFILIADO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_BENEFICIARIO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_APORTANTE] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[PREGUNTA] [nvarchar](255) NOT NULL,
	[SERVICIO] [nvarchar](40) NOT NULL,
    [NPS] [nvarchar](40) NOT NULL,
    [CALIFICACION] [nvarchar](255) NOT NULL,
	CONSTRAINT [PK_FACT_ENCUESTAS] PRIMARY KEY CLUSTERED ([ID_ENCUESTA]),
	CONSTRAINT [FK_FACT_ENCUESTAS_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD]),
	CONSTRAINT [FK_FACT_ENCUESTAS_DIM_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [Transversal].[DIM_EMPRESAS]([ID_EMPRESA]),
	CONSTRAINT [FK_FACT_ENCUESTAS_DIM_AFILIADOS] FOREIGN KEY ([ID_AFILIADO]) REFERENCES [Transversal].[DIM_AFILIADOS]([ID_AFILIADO]),
	CONSTRAINT [FK_FACT_ENCUESTAS_DIM_BENEFICIARIOS] FOREIGN KEY ([ID_BENEFICIARIO]) REFERENCES [Transversal].[DIM_BENEFICIARIOS]([ID_BENEFICIARIO]),
	CONSTRAINT [FK_FACT_ENCUESTAS_DIM_APORTANTE_NOAFILIADO] FOREIGN KEY ([ID_APORTANTE]) REFERENCES [Transversal].[DIM_APORTANTE_NOAFILIADO]([ID_APORTANTE]),
	CONSTRAINT [FK_FACT_ENCUESTAS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO
-- Crear FACT_ENCUESTAS_PSR
 CREATE TABLE [Transversal].[FACT_ENCUESTAS_PSR] (
    [ID_ENCUESTA_PSR] [int] IDENTITY(1,1) NOT NULL,
	[ID_FECHA] [int] NULL DEFAULT 20090101, -- Asignar valor por defecto de 1 de enero de 2009,
	[FECHA_ENCUESTA] [datetime] NOT NULL,
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
	[ID_EMPRESA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_AFILIADO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_BENEFICIARIO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_APORTANTE] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [DOCUMENTO] [nvarchar](20) NOT NULL,
    [PROGRAMA] [nvarchar](40) NOT NULL,
    [ACTIVIDAD_PREGUNTA] [nvarchar](255) NOT NULL,
    [CALIFICACION] [nvarchar](40) NOT NULL,
	CONSTRAINT [PK_FACT_ENCUESTAS_PSR] PRIMARY KEY CLUSTERED ([ID_ENCUESTA_PSR]),
	CONSTRAINT [FK_FACT_ENCUESTAS_PSR_DIM_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [Transversal].[DIM_EMPRESAS]([ID_EMPRESA]),
	CONSTRAINT [FK_FACT_ENCUESTAS_PSR_DIM_AFILIADOS] FOREIGN KEY ([ID_AFILIADO]) REFERENCES [Transversal].[DIM_AFILIADOS]([ID_AFILIADO]),
	CONSTRAINT [FK_FACT_ENCUESTAS_PSR_DIM_BENEFICIARIOS] FOREIGN KEY ([ID_BENEFICIARIO]) REFERENCES [Transversal].[DIM_BENEFICIARIOS]([ID_BENEFICIARIO]),
	CONSTRAINT [FK_FACT_ENCUESTAS_PSR_DIM_APORTANTE_NOAFILIADO] FOREIGN KEY ([ID_APORTANTE]) REFERENCES [Transversal].[DIM_APORTANTE_NOAFILIADO]([ID_APORTANTE]),
	CONSTRAINT [FK_FACT_ENCUESTAS_PSR_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO
-- Crear DIM_SEDES
 CREATE TABLE [Transversal].[DIM_SEDES] (
    [ID_SEDE] [int] IDENTITY(1,1) NOT NULL,
    [SEDE] [nvarchar](60),
	CONSTRAINT [PK_DIM_SEDES] PRIMARY KEY CLUSTERED ([ID_SEDE])
)
GO
-- Crear DIM_CAPACIDAD_FISICA
 CREATE TABLE [Transversal].[DIM_CAPACIDAD_FISICA] (
	[ID_CAPACIDAD] [int] IDENTITY(1,1) NOT NULL,
    [ID_SALON] [nvarchar](10) NOT NULL,
    [CAPACIDAD] [int] NOT NULL,
	[DESCRIPCION_ESPACIO] [nvarchar](255),
    [JORNADA] [nvarchar](40),
    [BLOQUE] [nvarchar](40),
    [GRUPO] [nvarchar](40),
    [ID_UNIDAD] [int] NULL DEFAULT 5, -- Asignar valor por defecto de 5
    [ID_SEDE] [int] NOT NULL,
    [SEDE] [nvarchar](40),
    [ESTADO] [nvarchar](40),
	[FECHA_ESTADO] [datetime] NOT NULL,
	[ID_CAPACIDAD_AUXILIAR] AS ( [ID_SALON] + '_' + [JORNADA] + '_' + CAST([ID_UNIDAD] AS NVARCHAR(10)) ) PERSISTED,
	CONSTRAINT [PK_DIM_CAPACIDAD_FISICA] PRIMARY KEY CLUSTERED ([ID_CAPACIDAD]),
	CONSTRAINT [FK_DIM_CAPACIDAD_FISICA_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD]),
	CONSTRAINT [FK_DIM_CAPACIDAD_FISICA_DIM_SEDES] FOREIGN KEY ([ID_SEDE]) REFERENCES [Transversal].[DIM_SEDES]([ID_SEDE])
)
GO


-- Crear FACT_INICIATIVAS
 CREATE TABLE [Transversal].[FACT_INICIATIVAS] (
    [ID_INICIATIVA] [int] IDENTITY(1,1) NOT NULL,
	[ID_FECHA] [int] NULL DEFAULT 20090101, -- Asignar valor por defecto de 1 de enero de 2009,
    [ID_UNIDAD] [int] NULL DEFAULT 5, -- Asignar valor por defecto de 5
    [FECHA_INICIO] [datetime] NOT NULL,
    [FECHA_FIN] [datetime] NOT NULL,
    [NOMBRE_INICIATIVA] [nvarchar](255),
    [DESCRIPCION_INICIATIVA] [nvarchar](255),
    [OBSERVACIONES] [nvarchar](255),
	CONSTRAINT [PK_FACT_INICIATIVAS] PRIMARY KEY CLUSTERED ([ID_INICIATIVA]),
	CONSTRAINT [FK_FACT_INICIATIVAS_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD]),
	CONSTRAINT [FK_FACT_INICIATIVAS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO
-- Crear FACT_PQRS
 CREATE TABLE [Transversal].[FACT_PQRS] (
    [ID_PQR] [nvarchar](40) NOT NULL,
    [ID_UNIDAD] [int] NULL DEFAULT 5, -- Asignar valor por defecto de 5
	[ID_FECHA] [int] NULL DEFAULT 20090101, -- Asignar valor por defecto de 1 de enero de 2009,
    [ASUNTO] [nvarchar](255),
    [CREADO_POR] [nvarchar](255),
    [ASIGNADO_A] [nvarchar](255),
    [ESTADO] [nvarchar](40),
    [TIPO_DOCUMENTO] [nvarchar](40),
    [DOCUMENTO] [nvarchar](20),
    [NOMBRE] [nvarchar](255),
	[ID_EMPRESA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_AFILIADO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_BENEFICIARIO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
	[ID_APORTANTE] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [FECHA_CREACION] [datetime] NOT NULL,
    [FECHA_RESOLUCION] [datetime] NOT NULL,
    [FECHA_VENCIMIENTO] [datetime] NOT NULL,
    [EQUIPO] [nvarchar](40),
    [UNIDAD] [nvarchar](255),
    [PROGRAMA_INCIDENTE] [nvarchar](255),
    [ID_CAUSA] [nvarchar](40),
    [CAUSA] [nvarchar](40),
    [TIPO_PQRS] [nvarchar](40),
    [TIPO_RESOLUCION] [nvarchar](40),
    [UBICACION] [nvarchar](255),
	CONSTRAINT [PK_FACT_PQRS] PRIMARY KEY CLUSTERED ([ID_PQR]),
	CONSTRAINT [FK_FACT_PQRS_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD]),
	CONSTRAINT [FK_FACT_PQRS_DIM_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [Transversal].[DIM_EMPRESAS]([ID_EMPRESA]),
	CONSTRAINT [FK_FACT_PQRS_DIM_AFILIADOS] FOREIGN KEY ([ID_AFILIADO]) REFERENCES [Transversal].[DIM_AFILIADOS]([ID_AFILIADO]),
	CONSTRAINT [FK_FACT_PQRS_DIM_BENEFICIARIOS] FOREIGN KEY ([ID_BENEFICIARIO]) REFERENCES [Transversal].[DIM_BENEFICIARIOS]([ID_BENEFICIARIO]),
	CONSTRAINT [FK_FACT_PQRS_DIM_APORTANTE_NOAFILIADO] FOREIGN KEY ([ID_APORTANTE]) REFERENCES [Transversal].[DIM_APORTANTE_NOAFILIADO]([ID_APORTANTE]),
	CONSTRAINT [FK_FACT_PQRS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO
-- Crear FACT_CONVENIOS
 CREATE TABLE [Transversal].[FACT_CONVENIOS] (
    [ID_CONVENIO] [int] IDENTITY(1,1) NOT NULL,
	[ID_FECHA] [int] NULL DEFAULT 20090101, -- Asignar valor por defecto de 1 de enero de 2009,
    [ID_UNIDAD] [int],-- NOT NULL,
    [ID_PROGRAMA] [int] NOT NULL,
    [UNIDAD] [nvarchar](40),
    [PROGRAMA] [nvarchar](40),
    [NOMBRE_CONVENIO] [nvarchar](255),
    [IDENTIFICACION_ACTO_CONVENIO] [nvarchar](255),
    [ENTIDAD_CONVENIO] [nvarchar](255),
    [COD_MUNICIPIO] [nvarchar](40),
    [VALOR_CONVENIO] [decimal](28, 2) NOT NULL,
    [APORTE_COMFENALCO] [nvarchar](40),
    [ESTADO_CONVENIO] [nvarchar](40),
    [FECHA_INICIO] [datetime] NOT NULL,
    [FECHA_FIN] [datetime] NOT NULL,
	CONSTRAINT [PK_FACT_CONVENIOS] PRIMARY KEY CLUSTERED ([ID_CONVENIO]),
	--CONSTRAINT [FK_FACT_CONVENIOS_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD]),
	CONSTRAINT [FK_FACT_CONVENIOS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)

GO
-- Tablas para el cubo
CREATE TABLE [Transversal].[FACT_MINERIA](
	[BP] [nvarchar](20) NULL,
	[ID_FECHA_MENSUAL] [int] NULL,
	[ID_ANIO_ACADEMICO] [nvarchar](4) NULL,
	[ID_UNIDAD] [int] NULL,
	[FECHA_INICIAL] [datetime] NULL,
	[FECHA_FINAL] [datetime] NULL,
	[ACTIVIDAD] [nvarchar](100) NULL,
	[TIEMPO_SEGUNDOS] [int] NULL,
	[VALOR_PAGADO] [int] NULL,
	[ID_CATEGORIA] [int] NULL,
	[ID_CURSO] [int] NULL,
	[ID_TIPO_ESTUDIANTE] [int] NULL,
	[ID_PROGRAMA] [int] NULL DEFAULT -1,
	[FUENTE_PRINCIPAL] NVARCHAR(250) NULL
) ON [PRIMARY]
GO
CREATE TABLE [Transversal].[DIM_TIEMPO_MENSUAL](
	[ID_FECHA] [int] NULL,
	[FECHA] [datetime] NULL,
	[DESC_FECHA] [nvarchar](50) NULL,
	[ID_SEMANA] [int] NULL,
	[DESC_SEMANA] [nvarchar](50) NULL,
	[ID_NO_MES] [int] NULL,
	[DESC_NO_MES] [nvarchar](50) NULL,
	[ID_MES] [int] NULL,
	[DESC_MES] [nvarchar](50) NULL,
	[DESC_MES_CORTA] [nvarchar](50) NULL,
	[ID_BIMESTRE] [int] NULL,
	[DESC_BIMESTRE] [nvarchar](50) NULL,
	[ID_TRIMESTRE] [int] NULL,
	[DESC_TRIMESTRE] [nvarchar](50) NULL,
	[ID_CUATRIMESTRE] [int] NULL,
	[DESC_CUATRIMESTRE] [nvarchar](50) NULL,
	[ID_SEMESTRE] [int] NULL,
	[DESC_SEMESTRE] [nvarchar](50) NULL,
	[ID_ANIO] [int] NULL,
	[ID_ANIO_ANT] [int] NULL,
	[NUM_DIA_SEMANA] [int] NULL,
	[FESTIVO] [int] NULL,
	[FECHA_CORTA] [date] NULL,
	[FUENTE_PRINCIPAL] NVARCHAR(250) NULL
) ON [PRIMARY]
GO
CREATE TABLE [DWH_COMFENALCO].[Transversal].[FACT_UNIDADES] (
    ID_CURSO INT,
    GRADO VARCHAR(255),
    ID_UNIDAD INT,
    CATEGORIA VARCHAR(255),
    ID_PLAN_COBERTURA INT,
    ID_ESTABLECIMIENTO_EDUCATIVO VARCHAR(255),
    ID_PROGRAMA INT,
    ID_FECHA_MENSUAL INT,
    POBLACION_PROYECTADA INT,
    ORIGEN VARCHAR(255),
    ACTIVIDAD VARCHAR(255),
    RESULTADO VARCHAR(255),
    CATEGORIA_SABER11 VARCHAR(255),
    CAUSA VARCHAR(255),
    NUM_POBLACION INT,
	CALIFICACION VARCHAR(255),
	DOCUMENTOS_COMPLETOS VARCHAR(255),
	NUM_ESTUDIANTES INT,
	NUM_MAYOR_250 INT,
	TEMATICA VARCHAR(255),
	[FUENTE_PRINCIPAL] NVARCHAR(250) NULL
)
GO
 CREATE TABLE [DWH_COMFENALCO].[Transversal].[FACT_PERSONAL] (
    ID_FECHA INT NULL,
    ID_PERSONAL INT NULL,
    NOMBRE NVARCHAR(255) ,
    CONCEPTO NVARCHAR(50) NULL,
    DESCRIPCION NVARCHAR(255) ,
    FECHA_FIN DATETIME ,
    HORAS_CONTRATADAS_MENSUAL INT ,
	ID_UNIDAD INT,
	[FUENTE_PRINCIPAL] NVARCHAR(250) NULL
)
GO
CREATE TABLE [DWH_COMFENALCO].[Transversal].[FACT_FINANCIERA] (
	[ID_FECHA] [int] NULL,
	[ID_ANIO] [int] NULL,
	[ID_MES] [int] NULL,
	[ID_CEBE] [bigint] NULL,
	[CEBE] [nvarchar](10) NULL,
	[DESCRIPCION_CEBE] [nvarchar](131) NULL,
	[DEPARTAMENTO] [nvarchar](100) NULL,
	[AREA] [nvarchar](100) NULL,
	[SUBAREA] [nvarchar](100) NULL,
	[SEGMENTO] [bigint] NULL,
	[DESCRIPCION_SEGMENTO] [nvarchar](50) NULL,
	[CODIGO_SSF] [int] NULL,
	[NOMBRE_SSF] [nvarchar](100) NULL,
	[ID_CUENTA] [bigint] NULL,
	[CUENTA] [nvarchar](10) NULL,
	[CUENTA_HOMOLOGA] [nvarchar](10) NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
	[TIPO_CUENTA] [nvarchar](100) NULL,
	[TIPO_OPERACION] [nvarchar](100) NULL,
	[GRUPO_CUENTA] [nvarchar](100) NULL,
	[SUBGRUPO_CUENTA] [nvarchar](50) NULL,
	[GRUPO_OPERACION] [nvarchar](100) NULL,
	[CUENTA_SSF] [int] NULL,
	[DESCRIPCION_SSF] [nvarchar](255) NULL,
	[CUENTA_DESCRIPCION] [nvarchar](61) NULL,
	[CUENTA_DESCRIPCION_SSF] [nvarchar](286) NULL,
	[SIGNO_INGRESOS] [int] NULL,
	[CLASIFICACION] [int] NULL,
	[SEGMENT] [bigint] NULL,
	[IMPORTE] [numeric](18, 0) NULL,
	[INGRESOS] [numeric](18, 0) NULL,
	[INGRESOS_OPERACIONALES] [numeric](18, 0) NULL,
	[GASTOS] [numeric](18, 0) NULL,
	[GASTOS_OPERACIONALES] [numeric](18, 0) NULL,
	[GASTOS_OPERACIONALES_ADMIN] [numeric](18, 0) NULL,
	[RESULTADO_EJERCICIO] [numeric](18, 0) NULL,
	[COSTOS] [numeric](18, 0) NULL,
	[ACTIVO] [numeric](18, 0) NULL,
	[PASIVO] [numeric](18, 0) NULL,
	[PATRIMONIO] [numeric](18, 0) NULL,
	[GASTOS_CON_DISTRIBUCION] [numeric](18, 0) NULL,
	[GASTOS_SIN_DISTRIBUCION] [numeric](18, 0) NULL,
	[TIPO] [nvarchar](7) NULL,
	[ACTIVIDAD] [nvarchar](20) NULL,
	[FUENTE_PRINCIPAL] [nvarchar](36) NULL,
	[ID_UNIDAD] int NULL
) ON [PRIMARY]
GO
 CREATE TABLE [DWH_COMFENALCO].[Transversal].[FACT_EVALUACION_DOCENTE] (
 PERIODO_ACADEMICO NVARCHAR(50)
,ID_UNIDAD INT
,ID_PERSONAL INT NULL
,NOMBRE_DOCENTE NVARCHAR(255)
,CALIFICACION_DEFINITIVA NVARCHAR(50)
, ID_FECHA INT NULL
,[FUENTE_PRINCIPAL] NVARCHAR(250) NULL
)
GO
CREATE TABLE [DWH_COMFENALCO].[Transversal].[FACT_ACTIVIDADES] (
    [ACTIVIDAD] NVARCHAR(255),
    [ADEUDA] DECIMAL(18, 2) NULL,
    [ANIO_ACADEMICO] INT NULL,
    [CANTIDAD_MATERIAL] INT NULL,
    [CALIFICACION] NVARCHAR(255) NULL,
    [CAUSA] NVARCHAR(255) NULL,
    [CATEGORIA_VENTA] NVARCHAR(255) NULL,
    [COSTO] DECIMAL(18, 2) NULL,
    [CURSO] NVARCHAR(255) NULL,
    [DESCRIPCION] NVARCHAR(255) NULL,
    [ESTADO] NVARCHAR(255) NULL,
    [ESTADOREGISTRO] NVARCHAR(50),
    [ESTADO_PAGO] NVARCHAR(255) NULL,
    [ESTRATO] INT NULL,
	[DISCAPACIDAD] NVARCHAR (10) NULL,
	[EDAD] INT NULL,
	[FECHA_NACIMIENTO] DATETIME NULL,
    [FECHA_AFILIACION] DATE NULL,
    [FECHA_MENSUAL] DATE,
    [FECHA_RETIRO] DATE NULL,
    [FECHA_ADMISION] DATE NULL,
    [ID_AFILIADO] INT NULL,
    [ID_CATEGORIA] INT NULL,
    [ID_CIUDAD] INT NULL,
    [ID_CONCEPTO] INT NULL,
    [ID_CURSO] INT NULL,
    [ID_EMPRESA] INT NULL,
    [ID_ESTADO_CIVIL] INT NULL,
    [ID_ESTADO_GESTION] INT NULL,
    [ID_FACTOR_VULNERABILIDAD] INT NULL,
    [ID_FECHA] INT,
    [ID_GENERO] INT NULL,
    [ID_GRADO] INT NULL,
    [ID_MATERIAL] INT NULL,
    [ID_PERTENENCIA_ETNICA] INT NULL,
    [ID_POBLACION] INT NULL,
    [ID_PROGRAMA] INT NULL,
    [ID_PREGUNTA] INT NULL,
    [ID_TIPO_AFILIADO] INT NULL,
    [ID_UNIDAD] INT NULL,
    [NO_PRESTAMOS] INT NULL,
    [NUMERO_APORTES] INT,
    [PARTNER] NVARCHAR(50),
    [PARTNER_AFILIADO] NVARCHAR(50) NULL,
    [PARTNER_EMPRESA] NVARCHAR(50) NULL,
    [RESPUESTA] NVARCHAR(255) NULL,
    [SALARIO_BASICO] DECIMAL(18, 2) NULL,
    [SERVICIO_TRANSPORTE] NVARCHAR(255) NULL,
    [SUBSIDIO] DECIMAL(20, 2) NULL,
    [TIPO_AFILIADO] NVARCHAR(255) NULL,
    [TIPO_POBLACION] NVARCHAR(50),
    [TOTAL_APORTES] DECIMAL(18, 2),
    [VALOR_FACTURADO] DECIMAL(18, 2) NULL,
    [VALOR_MATERIAL] DECIMAL(18, 2) NULL,
    [VALOR_PAGADO] DECIMAL(18, 2) NULL,
    [VALOR_PAGADO_SIN_IMP] DECIMAL(18, 2) NULL,
	[POBLACION_EDUCACION] NVARCHAR(50) NULL,
	[POBLACION_EDUCACION_FORMAL] NVARCHAR(50) NULL,
	[POBLACION_EDUCACION_TECNICA] NVARCHAR(50) NULL,
	[POBLACION_EDUCACION_CONTINUA] NVARCHAR(50) NULL,
	[POBLACION_EDUCACION_PROTECCION] NVARCHAR(50) NULL,
	[FUENTE_PRINCIPAL] NVARCHAR(250) NULL,
	[ID_PQR] [nvarchar](40) NULL DEFAULT -1,
	[ESTADO_PQR] [nvarchar](40),
	[ID_BENEFICIARIO] [int] NULL DEFAULT -1,
	[CAUSA_PQR] [nvarchar](40),
	[TIPO_PQRS] [nvarchar](40),
	[ID_TARIFA] [int] NULL DEFAULT -1,
	[ID_MATRICULA] [int] NULL DEFAULT -1,
	[ID_GRADUADO] [int] NULL DEFAULT -1,
	[ID_DESERCION] [int] NULL DEFAULT -1
)
GO

-- Tabla DIM_GENERO
CREATE TABLE [Transversal].[DIM_GENERO] (
    [ID_GENERO] INT PRIMARY KEY,
    [GENERO] NVARCHAR(50)
);

INSERT INTO [Transversal].[DIM_GENERO] ([ID_GENERO], [GENERO])
SELECT DISTINCT
    [ID_GENERO],
    [GENERO]
FROM [DWH_COMFENALCO].[Aportes].[DIM_AFILIADOS];

-- Tabla DIM_ORIENTACION_SEXUAL
CREATE TABLE [Transversal].[DIM_ORIENTACION_SEXUAL] (
    [ID_ORIENTACION_SEXUAL] INT PRIMARY KEY,
    [ORIENTACION_SEXUAL] NVARCHAR(50)
);

INSERT INTO [Transversal].[DIM_ORIENTACION_SEXUAL] ([ID_ORIENTACION_SEXUAL], [ORIENTACION_SEXUAL])
SELECT DISTINCT
    [ID_ORIENTACION_SEXUAL],
    [ORIENTACION_SEXUAL]
FROM [DWH_COMFENALCO].[Aportes].[DIM_AFILIADOS];

-- Tabla DIM_ESTADO_CIVIL
CREATE TABLE [Transversal].[DIM_ESTADO_CIVIL] (
    [ID_ESTADO_CIVIL] INT PRIMARY KEY,
    [ESTADO_CIVIL] NVARCHAR(50)
);

INSERT INTO [Transversal].[DIM_ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [ESTADO_CIVIL])
SELECT DISTINCT
    [ID_ESTADO_CIVIL],
    [ESTADO_CIVIL]
FROM [DWH_COMFENALCO].[Aportes].[DIM_AFILIADOS];

-- Tabla DIM_FACTOR_DE_VULNERABILIDAD
CREATE TABLE [Transversal].[DIM_FACTOR_DE_VULNERABILIDAD] (
    [ID_FACTOR_VULNERABILIDAD] INT PRIMARY KEY,
    [FACTOR_VULNERABILIDAD] NVARCHAR(50)
);

INSERT INTO [Transversal].[DIM_FACTOR_DE_VULNERABILIDAD] ([ID_FACTOR_VULNERABILIDAD], [FACTOR_VULNERABILIDAD])
SELECT DISTINCT
    [ID_FACTOR_VULNERABILIDAD],
    [FACTOR_VULNERABILIDAD]
FROM [DWH_COMFENALCO].[Aportes].[DIM_AFILIADOS];

-- Tabla DIM_PERTENENCIA_ETNICA
CREATE TABLE [Transversal].[DIM_PERTENENCIA_ETNICA] (
    [ID_PERTENENCIA_ETNICA] INT PRIMARY KEY,
    [PERTENENCIA_ETNICA] NVARCHAR(50)
);

INSERT INTO [Transversal].[DIM_PERTENENCIA_ETNICA] ([ID_PERTENENCIA_ETNICA], [PERTENENCIA_ETNICA])
SELECT DISTINCT
    [ID_PERTENENCIA_ETNICA]
      ,[PERTENENCIA_ETNICA]
FROM [DWH_COMFENALCO].[Aportes].[DIM_AFILIADOS];