USE DWH_COMFENALCO
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Eliminar restricciones de clave foránea
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'ALTER TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) 
    + ' DROP CONSTRAINT ' + QUOTENAME(f.name) + '; ' 
FROM sys.foreign_keys f
INNER JOIN sys.tables t ON f.parent_object_id = t.object_id
INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE s.name = 'Cedesarrollo';
EXEC sp_executesql @sql;
-- Eliminar tablas
SET @sql = '';
SELECT @sql += 'DROP TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) + '; ' 
FROM sys.tables t
INNER JOIN sys.schemas s ON t.schema_id = s.schema_id
WHERE s.name = 'Cedesarrollo';
EXEC sp_executesql @sql;
-- Eliminar el esquema
IF EXISTS (SELECT * FROM sys.schemas WHERE name = 'Cedesarrollo')
BEGIN
    DROP SCHEMA Cedesarrollo;
END
GO
-- Crear el esquema Cedesarrollo
CREATE SCHEMA Cedesarrollo;
GO 
-- Crear Cedesarrollo.DIM_ESTUDIANTES
CREATE TABLE [Cedesarrollo].[DIM_ESTUDIANTES] (
    [ID_ESTUDIANTE] [int] IDENTITY(1,1) NOT NULL,
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
    [DOCUMENTO] [nvarchar](20) NOT NULL,
    [ID_EMPRESA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
    [ID_AFILIADO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
    [ID_BENEFICIARIO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
    [ID_APORTANTE] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
	CONSTRAINT [PK_DIM_ESTUDIANTES] PRIMARY KEY CLUSTERED ([ID_ESTUDIANTE]),
	CONSTRAINT [FK_DIM_ESTUDIANTES_DIM_EMPRESAS] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [Transversal].[DIM_EMPRESAS]([ID_EMPRESA]),
	CONSTRAINT [FK_DIM_ESTUDIANTES_DIM_AFILIADOS] FOREIGN KEY ([ID_AFILIADO]) REFERENCES [Transversal].[DIM_AFILIADOS]([ID_AFILIADO]),
	CONSTRAINT [FK_DIM_ESTUDIANTES_DIM_BENEFICIARIOS] FOREIGN KEY ([ID_BENEFICIARIO]) REFERENCES [Transversal].[DIM_BENEFICIARIOS]([ID_BENEFICIARIO]),
	CONSTRAINT [FK_DIM_ESTUDIANTES_DIM_APORTANTE_NOAFILIADO] FOREIGN KEY ([ID_APORTANTE]) REFERENCES [Transversal].[DIM_APORTANTE_NOAFILIADO]([ID_APORTANTE])
)
GO
-- Crear Cedesarrollo.DIM_PERIODO_ACADEMICO
CREATE TABLE [Cedesarrollo].[DIM_PERIODO_ACADEMICO] (
    [ID_PERIODO] [int] IDENTITY(1,1) NOT NULL,
    [ID_UNIDAD] [int] NOT NULL,
    [PERIODO_ACADEMICO] [nvarchar](40),
    [FECHA_INICIO] [datetime] NULL, -- QUITE NOT
    [FECHA_FIN] [datetime] NULL, -- QUITE NOT
	CONSTRAINT [PK_DIM_PERIODO_ACADEMICO] PRIMARY KEY CLUSTERED ([ID_PERIODO]),
	CONSTRAINT [FK_DIM_PERIODO_ACADEMICO_DIM_UNIDAD] FOREIGN KEY ([ID_UNIDAD]) REFERENCES [Transversal].[DIM_UNIDAD]([ID_UNIDAD])
)
GO
-- Crear Cedesarrollo.DIM_PROGRAMA
CREATE TABLE [Cedesarrollo].[DIM_PROGRAMA] (
	[ID_PROGRAMA] [int] IDENTITY(1,1) NOT NULL,
    [PROGRAMA] [nvarchar](255)
	CONSTRAINT [PK_DIM_PROGRAMA] PRIMARY KEY CLUSTERED ([ID_PROGRAMA])
)
GO

-- Crear Cedesarrollo.DIM_JORNADA
CREATE TABLE [Cedesarrollo].[DIM_JORNADA] (
    [ID_JORNADA] [int] IDENTITY(1,1) NOT NULL,
    [ID_UNIDAD] [int] NOT NULL,
    [JORNADA] [nvarchar](40),
	CONSTRAINT [PK_DIM_JORNADA] PRIMARY KEY CLUSTERED ([ID_JORNADA])
)
GO

-- Crear Cedesarrollo.DIM_PLAN_CURRICULAR
CREATE TABLE [Cedesarrollo].[DIM_PLAN_CURRICULAR] (
	[ID_MODULO] [int] IDENTITY(1,1) NOT NULL,
    [ID_PROGRAMA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1,
    [MODULO] [nvarchar](200), 
    --[ID_PERIODO] [int] NOT NULL,
    [INTENSIDAD_HORARIA] [nvarchar](40),
    [INTENSIDAD_HORARIA_SEMANAL] [nvarchar](40),
    [NO_CREDITOS] [nvarchar](40),
    [SEMESTRE] [nvarchar](40),
	CONSTRAINT [PK_DIM_PLAN_CURRICULAR] PRIMARY KEY CLUSTERED ([ID_MODULO]),
	CONSTRAINT [FK_DIM_PLAN_CURRICULAR_DIM_PROGRAMA] FOREIGN KEY ([ID_PROGRAMA]) REFERENCES [Cedesarrollo].[DIM_PROGRAMA]([ID_PROGRAMA])
)
GO

-- Crear Cedesarrollo.FACT_NOTAS
CREATE TABLE [Cedesarrollo].[FACT_NOTAS] (
    [ID_NOTA] [int] IDENTITY(1,1) NOT NULL,
    [SEDE] [nvarchar](255),
    [ID_JORNADA] [int] NOT NULL,
    [ID_MODULO] [int] NULL,  -- QUITE NULL
    [CURSO] [nvarchar](40),
    [FECHA_INICIO] [datetime] NULL, -- QUITE NULL
    [ID_PERIODO] [int] NOT NULL,
    --[PROGRAMA_ACADEMICO] [nvarchar](60),
    [ID_PERSONAL] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [NOMBRE_DOCENTE] [nvarchar](200),
    [FECHA_FIN] [datetime] NULL, -- QUITE NULL
    [ID_ESTUDIANTE] [int] NOT NULL,
    [NOMBRE_ESTUDIANTE] [nvarchar](200),
    [PRIMER_CORTE] [decimal](10, 2),
    [PRIMER_CORTE_CP1] [decimal](10, 2),
    [PRIMER_CORTE_CP2] [decimal](10, 2),
    [PRIMER_CORTE_CT1] [decimal](10, 2),
    [PRIMER_CORTE_CT2] [decimal](10, 2),
    [SEGUNDO_CORTE] [decimal](10, 2),
    [SEGUNDO_CORTE_CP1] [decimal](10, 2),
    [SEGUNDO_CORTE_CP2] [decimal](10, 2),
    [SEGUNDO_CORTE_CT1] [decimal](10, 2),
    [SEGUNDO_CORTE_CT2] [decimal](10, 2),
    [TERCER_CORTE] [decimal](10, 2),
    [TERCER_CORTE_CP1] [decimal](10, 2),
    [TERCER_CORTE_CP2] [decimal](10, 2),
    [TERCER_CORTE_CT1] [decimal](10, 2),
    [TERCER_CORTE_CT2] [decimal](10, 2),
    [NOTA_FINAL] [decimal](10, 2),
    [PESO_CORTE] [decimal](10, 2),
	CONSTRAINT [PK_FACT_NOTAS] PRIMARY KEY CLUSTERED ([ID_NOTA]),
	CONSTRAINT [FK_FACT_NOTAS_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_NOTAS_DIM_PERSONAL] FOREIGN KEY ([ID_PERSONAL]) REFERENCES [Transversal].[DIM_PERSONAL]([ID_PERSONAL]),
	CONSTRAINT [FK_FACT_NOTAS_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_NOTAS_DIM_PLAN_CURRICULAR] FOREIGN KEY ([ID_MODULO]) REFERENCES [Cedesarrollo].[DIM_PLAN_CURRICULAR]([ID_MODULO]),
	CONSTRAINT [FK_FACT_NOTAS_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA])

)
GO

-- Crear Cedesarrollo.FACT_HORARIO
CREATE TABLE [Cedesarrollo].[FACT_HORARIO] (
	[ID_HORARIO] [int] IDENTITY(1,1) NOT NULL,
    [ID_PERIODO] [int] NOT NULL,
    --[PROGRAMA] [nvarchar](40),
	[ID_MODULO] [int] NULL,
    --[MODULO] [nvarchar](40),
	[ID_JORNADA] [int] NULL,
    --[JORNADA] [nvarchar](40),
    [SEMESTRE] [nvarchar](40),
    [GRUPO] [nvarchar](40),
    [DIA] [nvarchar](40),
    [SALON] [nvarchar](40),
    [HORA_INICIO] [nvarchar](40),
    [HORA_FIN] [nvarchar](40),
    [ID_PERSONAL] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [NOMBRE_DOCENTE] [nvarchar](200),
    [COD_ESTABLECIMIENTO] [nvarchar](40),
	CONSTRAINT [PK_FACT_HORARIO] PRIMARY KEY CLUSTERED ([ID_HORARIO]),
	CONSTRAINT [FK_FACT_HORARIO_DIM_PERSONAL] FOREIGN KEY ([ID_PERSONAL]) REFERENCES [Transversal].[DIM_PERSONAL]([ID_PERSONAL]),
	CONSTRAINT [FK_FACT_HORARIO_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_HORARIO_DIM_PLAN_CURRICULAR] FOREIGN KEY ([ID_MODULO]) REFERENCES [Cedesarrollo].[DIM_PLAN_CURRICULAR]([ID_MODULO]),
	CONSTRAINT [FK_FACT_HORARIO_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA])
)
GO



-- Crear Cedesarrollo.FACT_AUSENTISMO_DOCENTE
CREATE TABLE [Cedesarrollo].[FACT_AUSENTISMO_DOCENTE] (
	[ID_AUSENTISMO_DOCENTE] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERIODO] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [FECHA] [datetime] NOT NULL,
    [ID_FECHA] [int] NOT NULL,
    [ID_PERSONAL] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [NOMBRE_DOCENTE] [nvarchar](200),
    [CARGO] [nvarchar](40),
    [FECHA_INICIO] [datetime] NOT NULL,
    [FECHA_FIN] [datetime] NOT NULL,
    [AUSENCIA_HORAS] [nvarchar](40),
    [AUSENCIA_DIAS] [nvarchar](40),
    [TIPO_AUSENCIA] [nvarchar](40),
    [PERMISO] [nvarchar](40),
    [MOTIVO_AUSENCIA] [nvarchar](40),
	CONSTRAINT [PK_FACT_AUSENTISMO_DOCENTE] PRIMARY KEY CLUSTERED ([ID_AUSENTISMO_DOCENTE]),
	CONSTRAINT [FK_FACT_AUSENTISMO_DOCENTE_DIM_PERSONAL] FOREIGN KEY ([ID_PERSONAL]) REFERENCES [Transversal].[DIM_PERSONAL]([ID_PERSONAL]),
	CONSTRAINT [FK_FACT_AUSENTISMO_DOCENTE_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_AUSENTISMO_DOCENTE_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_PERMISO_ESTUDIANTE
CREATE TABLE [Cedesarrollo].[FACT_PERMISO_ESTUDIANTE] (
	[ID_PERMISO_ESTUDIANTE] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERIODO] [int] NOT NULL,
    [ID_ESTUDIANTE] [int] NOT NULL,
    --[PROGRAMA] [nvarchar](40),
    [MODULO] [nvarchar](40),
	[ID_FECHA] [int] NOT NULL,
    [FECHA] [datetime] NOT NULL,
    [HORA] [nvarchar](40),
    [MOTIVO_AUSENCIA] [nvarchar](40),
    [SOPORTE_AUSENCIA] [nvarchar](40),
	CONSTRAINT [PK_FACT_PERMISO_ESTUDIANTE] PRIMARY KEY CLUSTERED ([ID_PERMISO_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_PERMISO_ESTUDIANTE_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_PERMISO_ESTUDIANTE_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_PERMISO_ESTUDIANTE_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_INASISTENCIAS
CREATE TABLE [Cedesarrollo].[FACT_INASISTENCIAS] (
	[ID_INASISTENCIAS] [int] IDENTITY(1,1) NOT NULL,
    [ID_ESTUDIANTE] [int] NOT NULL,
	[ID_PERIODO] [int] NOT NULL,
    [DOCUMENTO] [nvarchar](20) NOT NULL,
    --[PROGRAMA] [nvarchar](40),
    [SEDE] [nvarchar](255),
	[ID_JORNADA] [int] NOT NULL,
    --[JORNADA] [nvarchar](40),
	[ID_MODULO] [int] NULL, -- QUITE NOT
    --[MODULO] [nvarchar](40),
    [CURSO] [nvarchar](40) NULL,
    [CORTE] [nvarchar](40) NULL,
	[ID_FECHA] [int] NULL, -- QUITE NOT
    [FECHA] [datetime] NULL, -- QUITE NOT
    [HORA] [nvarchar](40) NULL,
    [TOTAL_INASISTENCIA] [nvarchar](40),
	CONSTRAINT [PK_FACT_INASISTENCIAS] PRIMARY KEY CLUSTERED ([ID_INASISTENCIAS]),
	CONSTRAINT [FK_FACT_INASISTENCIAS_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_INASISTENCIAS_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_INASISTENCIAS_DIM_PLAN_CURRICULAR] FOREIGN KEY ([ID_MODULO]) REFERENCES [Cedesarrollo].[DIM_PLAN_CURRICULAR]([ID_MODULO]),
	CONSTRAINT [FK_FACT_INASISTENCIAS_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA]),
	CONSTRAINT [FK_FACT_INASISTENCIAS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_DESERCION
CREATE TABLE [Cedesarrollo].[FACT_DESERCION] (
	[ID_DESERCION] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERIODO] [int] NULL, /* NOT lo quite temporalmente ya que se llena posteriormente en la ETL*/
    [SEDE] [nvarchar](255),
	[ID_JORNADA] [int] NULL, /* NOT lo quite temporalmente ya que se llena posteriormente en la ETL*/
    --[JORNADA] [nvarchar](40),
    --[PROGRAMA] [nvarchar](40),
	[ID_PROGRAMA] [int] NULL DEFAULT -1,
    [NOMBRE_ESTUDIANTE] [nvarchar](255),
    [ID_ESTUDIANTE] [int] NOT NULL,
    [GRUPO] [nvarchar](40),
    --[MODULO] [nvarchar](40),
    [SEMESTRE] [nvarchar](40),
	[ID_FECHA] [int] NULL, /* NOT lo quite temporalmente*/
    [FECHA] [datetime] NOT NULL,
    [TIPO] [nvarchar](40),
    [CAUSA] [nvarchar](40),
    [OBSERVACIONES] [nvarchar](255),
	CONSTRAINT [PK_FACT_DESERCION] PRIMARY KEY CLUSTERED ([ID_DESERCION]),
	CONSTRAINT [FK_FACT_DESERCION_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_DESERCION_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_DESERCION_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA]),
	CONSTRAINT [FK_FACT_DESERCION_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_ESTADO_MATRICULAS
CREATE TABLE [Cedesarrollo].[FACT_ESTADO_MATRICULAS] (
	[ID_MATRICULA] [int] IDENTITY(1,1) NOT NULL,
    [ID_PERIODO] [int] NULL,
	[ID_PROGRAMA] [int] NULL, -- QUITE NOT  
    [SEDE] [nvarchar](255),
	[ID_JORNADA] [int] NULL, -- QUITE NOT  
    --[JORNADA] [nvarchar](40),
    [NOMBRE_ESTUDIANTE] [nvarchar](200),
    [ID_ESTUDIANTE] [int] NOT NULL,
	[ID_FECHA] [int] NULL, -- QUITE NOT  
    [FECHA_MATRICULA] [datetime] NOT NULL,
    [TELEFONO] [nvarchar](40),
    [CELULAR] [nvarchar](40),
    [CORREO] [nvarchar](200),
    [FECHA_OPORTUNA] [datetime] NULL, -- QUITE NOT  
    [FECHA_ACTUALIZACION] [datetime] NULL, -- QUITE NOT  
    [DOCUMENTOS_COMPLETOS] [nvarchar](20) NULL, -- QUITE NOT  
    [SEMESTRE] [nvarchar](40),
	CONSTRAINT [PK_FACT_ESTADO_MATRICULAS] PRIMARY KEY CLUSTERED ([ID_MATRICULA]),
	CONSTRAINT [FK_FACT_ESTADO_MATRICULAS_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_ESTADO_MATRICULAS_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_ESTADO_MATRICULAS_DIM_PROGRAMA] FOREIGN KEY ([ID_PROGRAMA]) REFERENCES [Cedesarrollo].[DIM_PROGRAMA]([ID_PROGRAMA]),
	CONSTRAINT [FK_FACT_ESTADO_MATRICULAS_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA]),
	CONSTRAINT [FK_FACT_ESTADO_MATRICULAS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_INSCRIPCION_MATRICULAS
CREATE TABLE [Cedesarrollo].[FACT_INSCRIPCION_MATRICULAS] (
	[ID_INSCRIPCION] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERIODO] [int] NULL, -- QUITE NOT  
	[ID_PROGRAMA] [int] NOT NULL,
    --[TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
    --[DOCUMENTO_ESTUDIANTE] [nvarchar](20) NOT NULL,
    --[JORNADA] [nvarchar](40),
    --[PROGRAMA] [nvarchar](40),
	[ID_FECHA] [int] NULL, -- QUITE NOT  
    [FECHA] [datetime] NOT NULL,
	[ID_JORNADA] [int] NOT NULL,
    [ESTADO] [nvarchar](40),
    [TIPO_ESTUDIANTE] [nvarchar](40),
    [CATEGORIA_COBERTURA] [nvarchar](40),
    [CATEGORIA_SUBSIDIO] [nvarchar](40),
    [ID_ESTUDIANTE] [int] NOT NULL,
	CONSTRAINT [PK_FACT_INSCRIPCION_MATRICULAS] PRIMARY KEY CLUSTERED ([ID_INSCRIPCION]),
	CONSTRAINT [FK_FACT_INSCRIPCION_MATRICULAS_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_INSCRIPCION_MATRICULAS_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_INSCRIPCION_MATRICULAS_DIM_PROGRAMA] FOREIGN KEY ([ID_PROGRAMA]) REFERENCES [Cedesarrollo].[DIM_PROGRAMA]([ID_PROGRAMA]),
	CONSTRAINT [FK_FACT_INSCRIPCION_MATRICULAS_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA]),
	CONSTRAINT [FK_FACT_INSCRIPCION_MATRICULAS_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_FACTURACION
CREATE TABLE [Cedesarrollo].[FACT_FACTURACION] (
	[ID_FACTURACION] [int] IDENTITY(1,1) NOT NULL,
	[ID_PERIODO] [int]  NULL, -- NO HAY UN CAMPO ELEGIBLE
    [TIPO_DOCUMENTO_PAGO] [nvarchar](40) NOT NULL,
    [DOCUMENTO_PAGO] [nvarchar](20) NOT NULL,
	[ID_FECHA] [int] NOT NULL,
    [FECHA_CONTABLE] [datetime] NOT NULL,
    [ID_TARIFA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [ID_CONCEPTO] [int] NOT NULL,
    [CONCEPTO] [nvarchar](255),
    [VALOR_FACTURADO] [decimal](28, 2),
    [SUBSIDIO] [decimal](28, 2),
    [VALOR_PAGADO] [decimal](28, 2),
    [ADEUDA] [nvarchar](40),
    [ESTADO_PAGO] [nvarchar](40),
    [FECHA_OPORTUNA_PAGO] [datetime] NULL,
    [NO_RECIBO] [nvarchar](40),
	[CATEGORIA] [nvarchar](40),
	[FUENTE_RECURSOS] [nvarchar](40) NULL DEFAULT 'PROPIOS'
	CONSTRAINT [PK_FACT_FACTURACION] PRIMARY KEY CLUSTERED ([ID_FACTURACION]),
	--CONSTRAINT [FK_FACT_FACTURACION_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_FACTURACION_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO
-- Crear Cedesarrollo.DIM_PREGUNTAS_COTIZACION
CREATE TABLE [Cedesarrollo].[DIM_PREGUNTAS_COTIZACION] (
    [ID_PREGUNTA] [int] IDENTITY(1,1) NOT NULL,
    [PREGUNTA] [nvarchar](255),
    [OBSERVACIONES] [nvarchar](255),
	CONSTRAINT [PK_DIM_PREGUNTAS_COTIZACION] PRIMARY KEY CLUSTERED ([ID_PREGUNTA])
)
GO

-- Crear Cedesarrollo.FACT_COTIZACIONES
CREATE TABLE [Cedesarrollo].[FACT_COTIZACIONES] (
	[ID_COTIZACION] [int] IDENTITY(1,1) NOT NULL,
	[ID_FECHA] [int] NOT NULL,
    [FECHA_REGISTRO] [datetime] NOT NULL,
    [ID_ESTUDIANTE] [int] NOT NULL,
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
    [DOCUMENTO] [nvarchar](20) NOT NULL,
    [NOMBRE] [nvarchar](200),
    [ID_TARIFA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [ESTADO_COTIZACION] [nvarchar](40),
    [ID_PREGUNTA] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [RESPUESTA] [nvarchar](40),
	CONSTRAINT [PK_FACT_COTIZACIONES] PRIMARY KEY CLUSTERED ([ID_COTIZACION]),
	CONSTRAINT [FK_FACT_COTIZACIONES_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_COTIZACIONES_DIM_PREGUNTAS_COTIZACION] FOREIGN KEY ([ID_PREGUNTA]) REFERENCES [Cedesarrollo].[DIM_PREGUNTAS_COTIZACION]([ID_PREGUNTA]),
	CONSTRAINT [FK_FACT_COTIZACIONES_DIM_TARIFAS_SERVICIOS] FOREIGN KEY ([ID_TARIFA]) REFERENCES [Transversal].[DIM_TARIFAS_SERVICIOS]([ID_TARIFA]),
	CONSTRAINT [FK_FACT_COTIZACIONES_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO


-- Crear Cedesarrollo.FACT_PLAN_COBERTURA
CREATE TABLE [Cedesarrollo].[FACT_PLAN_COBERTURA] (
    [ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
    [ID_PERIODO] [int] NOT NULL,
    [ID_UNIDAD] [int] NOT NULL,
    [UNIDAD] [nvarchar](40),
    [MODALIDAD] [nvarchar](40),
    [CATEGORIA] [nvarchar](40),
	[ID_PROGRAMA] [int] NULL,
    --[PROGRAMA] [nvarchar](40),
    [USOS_PROYECTADOS] [nvarchar](40),
    [USUARIOS_PROYECTADOS] [nvarchar](40),
	CONSTRAINT [PK_FACT_PLAN_COBERTURA] PRIMARY KEY CLUSTERED ([ID_REGISTRO]),
	CONSTRAINT [FK_FACT_PLAN_COBERTURA_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	--CONSTRAINT [FK_FACT_PLAN_COBERTURA_DIM_PROGRAMA] FOREIGN KEY ([ID_PROGRAMA]) REFERENCES [Cedesarrollo].[DIM_PROGRAMA]([ID_PROGRAMA])
)
GO

-- Crear Cedesarrollo.FACT_DESEMPENHO_DOCENTE_DE
CREATE TABLE [Cedesarrollo].[FACT_DESEMPENHO_DOCENTE_DE] (
    [ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
    [ID_UNIDAD] [int] NULL DEFAULT 3, -- Asignar valor por defecto de 3
    [ID_PERSONAL] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [ID_PERIODO] [int] NOT NULL,
    [NOMBRE_DOCENTE] [nvarchar](200),
    [TIPO_DOCUMENTO_ENCUESTADO] [nvarchar](40) NOT NULL,
    [DOCUMENTO_ENCUESTADO] [nvarchar](20) NOT NULL,
	[ID_FECHA] [int] NOT NULL,
    [FECHA] [datetime] NOT NULL,
    [PROGRAMA] [nvarchar](40),
    [CALIFICACION] [nvarchar](40),
	CONSTRAINT [PK_FACT_DESEMPENHO_DOCENTE_DE] PRIMARY KEY CLUSTERED ([ID_REGISTRO]),
	CONSTRAINT [FK_FACT_DESEMPENHO_DOCENTE_DE_DIM_PERSONAL] FOREIGN KEY ([ID_PERSONAL]) REFERENCES [Transversal].[DIM_PERSONAL]([ID_PERSONAL]),
	CONSTRAINT [FK_FACT_DESEMPENHO_DOCENTE_DE_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_DESEMPENHO_DOCENTE_DE_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_DESEMPENHO_DOCENTE_CE
CREATE TABLE [Cedesarrollo].[FACT_DESEMPENHO_DOCENTE_CE] (
    [ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
    [ID_UNIDAD] [int] NULL DEFAULT 2, -- Asignar valor por defecto de 2
    [ID_PERSONAL] [int] NULL DEFAULT -1, -- Asignar valor por defecto de -1
    [ID_PERIODO] [int] NOT NULL,
    [NOMBRE_DOCENTE] [nvarchar](200),
    [TIPO_CONTRATACION] [nvarchar](40),
    [CALIFICACION_ESTUDIANTES] [nvarchar](40),
    [CALIFICACION_UNIDAD] [nvarchar](40),
    [CALIFICACION_DOCENTE] [nvarchar](40),
    [CALIFICACION_DEFINITIVA] [nvarchar](40),
	CONSTRAINT [PK_FACT_DESEMPENHO_DOCENTE_CE] PRIMARY KEY CLUSTERED ([ID_REGISTRO]),
	CONSTRAINT [FK_FACT_DESEMPENHO_DOCENTE_CE_DIM_PERSONAL] FOREIGN KEY ([ID_PERSONAL]) REFERENCES [Transversal].[DIM_PERSONAL]([ID_PERSONAL]),
	CONSTRAINT [FK_FACT_DESEMPENHO_DOCENTE_CE_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO])
)
GO

-- Crear Cedesarrollo.FACT_GRADUADOS
CREATE TABLE [Cedesarrollo].[FACT_GRADUADOS] (
    [ID_GRADUADO] [int] IDENTITY(1,1) NOT NULL,
    [ID_ESTUDIANTE] [int] NOT NULL,
	[ID_PERIODO] [int] NOT NULL,
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
    [DOCUMENTO] [nvarchar](20) NOT NULL,
    [ID_JORNADA] [int] NOT NULL,
    [ID_PROGRAMA] [int] NOT NULL,
    [GRUPO] [nvarchar](40),
    [ESTADO] [nvarchar](40),
    [ZONA] [nvarchar](40),
    [NIVEL_FORMACION] [nvarchar](40),
    [OCUPACION] [nvarchar](40),
    [SEDE] [nvarchar](255),
    [JORNADA] [nvarchar](40),
    [PROGRAMA] [nvarchar](255),
    [SEMESTRE] [nvarchar](40),
    [FECHA_ACTUALIZACION] [datetime] NOT NULL,
    [FECHA_GRADUADO] [datetime] NOT NULL,
    [ACTA_GRADUADO] [nvarchar](40),
    [FOLIO_GRADUADO] [nvarchar](40),
    [DIPLOMA_GRADUADO] [nvarchar](40),
	CONSTRAINT [PK_FACT_GRADUADOS] PRIMARY KEY CLUSTERED ([ID_GRADUADO]),
	CONSTRAINT [FK_FACT_GRADUADOS_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_GRADUADOS_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_GRADUADOS_DIM_PROGRAMA] FOREIGN KEY ([ID_PROGRAMA]) REFERENCES [Cedesarrollo].[DIM_PROGRAMA]([ID_PROGRAMA]),
	CONSTRAINT [FK_FACT_GRADUADOS_DIM_JORNADA] FOREIGN KEY ([ID_JORNADA]) REFERENCES [Cedesarrollo].[DIM_JORNADA]([ID_JORNADA])
)
GO

-- Crear Cedesarrollo.FACT_ASISTENCIA_ACT_BIENESTAR
CREATE TABLE [Cedesarrollo].[FACT_ASISTENCIA_ACT_BIENESTAR] (
    [ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
    [ID_PERIODO] [int] NOT NULL,
    [ID_ESTUDIANTE] [int] NOT NULL,
    [TIPO_DOCUMENTO] [nvarchar](40) NOT NULL,
    [DOCUMENTO] [nvarchar](20) NOT NULL,
	[ID_FECHA] [int] NOT NULL,
    [FECHA] [datetime] NOT NULL,
    [ACTIVIDAD] [nvarchar](40),
    [ASISTIO] [nvarchar](40),
	CONSTRAINT [PK_FACT_ASISTENCIA_ACT_BIENESTAR] PRIMARY KEY CLUSTERED ([ID_REGISTRO]),
	CONSTRAINT [FK_FACT_ASISTENCIA_ACT_BIENESTAR_DIM_ESTUDIANTES] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [Cedesarrollo].[DIM_ESTUDIANTES]([ID_ESTUDIANTE]),
	CONSTRAINT [FK_FACT_ASISTENCIA_ACT_BIENESTAR_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO]),
	CONSTRAINT [FK_FACT_ASISTENCIA_ACT_BIENESTAR_DE_Dim_TIEMPO] FOREIGN KEY([ID_FECHA]) REFERENCES [Dwh].[DIM_TIEMPO] ([ID_FECHA])
)
GO

-- Crear Cedesarrollo.FACT_EVALUACION_PLAN_CURRICULAR
CREATE TABLE [Cedesarrollo].[FACT_EVALUACION_PLAN_CURRICULAR] (
    [ID_REGISTRO] [int] IDENTITY(1,1) NOT NULL,
    [ID_UNIDAD] [int] NOT NULL,
    [UNIDAD] [nvarchar](40),
    [ID_PERIODO] [int] NOT NULL,
    [CALIFICACION] [nvarchar](40),
    [OBSERVACIONES] [nvarchar](40),
	CONSTRAINT [PK_FACT_EVALUACION_PLAN_CURRICULAR] PRIMARY KEY CLUSTERED ([ID_REGISTRO]),
	CONSTRAINT [FK_FACT_EVALUACION_PLAN_CURRICULAR_DIM_PERIODO_ACADEMICO] FOREIGN KEY ([ID_PERIODO]) REFERENCES [Cedesarrollo].[DIM_PERIODO_ACADEMICO]([ID_PERIODO])
)
GO

-- Crear Cedesarrollo.FACT_EVALUACION_FORMACION
CREATE TABLE [Cedesarrollo].[FACT_EVALUACION_FORMACION] (
	[ID_EVALUACION_FORMACION] [int] IDENTITY(1,1) NOT NULL,
    [TIPO_DOCUMENTO_ENCUESTADO] [nvarchar](40) NOT NULL,
    [DOCUMENTO_ENCUESTADO] [nvarchar](20) NOT NULL,
    [FECHA_REALIZACION_EVENTO] [datetime] NOT NULL,
    [ASPECTO_1] [nvarchar](40),
    [ASPECTO_2] [nvarchar](40),
    [ASPECTO_3] [nvarchar](40),
    [ASPECTO_4] [nvarchar](40),
    [ASPECTO_5] [nvarchar](40),
    [ASPECTO_6] [nvarchar](40),
    [ASPECTO_7] [nvarchar](40),
    [ASPECTO_8] [nvarchar](40),
    [ASPECTO_9] [nvarchar](40),
	CONSTRAINT [PK_FACT_EVALUACION_FORMACION] PRIMARY KEY CLUSTERED ([ID_EVALUACION_FORMACION]),
)
GO

-- Disable identity insert to manually insert -1 in the identity column
SET IDENTITY_INSERT [Cedesarrollo].[DIM_ESTUDIANTES] ON;

INSERT INTO [Cedesarrollo].[DIM_ESTUDIANTES] ([ID_ESTUDIANTE], [TIPO_DOCUMENTO], [DOCUMENTO], [ID_EMPRESA], [ID_AFILIADO], [ID_BENEFICIARIO], [ID_APORTANTE])
VALUES (-1, 'N/A', 'N/A', -1, -1, -1, -1);

-- Enable identity insert back
SET IDENTITY_INSERT [Cedesarrollo].[DIM_ESTUDIANTES] OFF;

