USE [STAGE_AREA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Transversal].[DIM_POBLACION_PROTECCION](
	[TIPO_DOCUMENTO] [nvarchar](20) NOT NULL,
	[DOCUMENTO] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[FACT_CARACTERIZACION_PROTECCION](
	[FECHA] [varchar](50) NULL,
	[TIPO_DOCUMENTO] [varchar](50) NULL,
	[DOCUMENTO] [varchar](50) NULL,
	[PROGRAMA] [varchar](255) NULL,
	[PREGUNTA] [varchar](255) NULL,
	[RESPUESTA] [varchar](255) NULL,
	[OBSERVACIONES] [varchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[TMP_ACUDIENTES_SAP](
	[BP_ACUDIENTE] [nvarchar](10) NULL,
	[OBJETO_SAP_ESTUDIANTE] [nvarchar](8) NULL,
	[BP_ESTUDIANTE] [nvarchar](10) NULL,
	[NUMERO_MATRICULA] [nvarchar](12) NULL,
	[TIPO_DOCUMENTO] [nvarchar](40) NULL,
	[NUMERO_DOCUMENTO] [nvarchar](20) NULL,
	[PRIMER_APELLIDO] [nvarchar](40) NULL,
	[SEGUNDO_APELLIDO] [nvarchar](40) NULL,
	[PRIMER_NOMBRE] [nvarchar](40) NULL,
	[SEGUNDO_NOMBRE] [nvarchar](40) NULL,
	[GENERO] [nvarchar](15) NULL,
	[ESTADO_CIVIL] [nvarchar](20) NULL,
	[PROFESION] [nvarchar](70) NULL,
	[FECHA_NACIMIENTO] [nvarchar](8) NULL,
	[PARENTESCO] [nvarchar](9) NULL,
	[RESPONSABLE_JURIDICO] [nvarchar](2) NULL,
	[TELEFONO] [nvarchar](30) NULL,
	[PAIS] [nvarchar](3) NULL,
	[CIUDAD] [nvarchar](40) NULL,
	[DIRECCION] [nvarchar](60) NULL,
	[CORREO] [nvarchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[TMP_DESERTORES_CEDESARROLLO](
	[PROGRAMA] [nvarchar](255) NULL,
	[NOMBRE_ESTUDIANTE] [nvarchar](255) NULL,
	[FECHA] [datetime] NULL,
	[TIPO] [nvarchar](255) NULL,
	[CAUSA] [nvarchar](255) NULL,
	[OBSERVACIONES] [nvarchar](255) NULL,
	[SEDE] [nvarchar](255) NULL,
	[JORNADA] [nvarchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[TMP_ENCUESTAS](
	[FECHA_ENCUESTA] [varchar](50) NULL,
	[DOCUMENTO] [varchar](50) NULL,
	[PREGUNTA] [varchar](255) NULL,
	[CALIFICACION] [varchar](255) NULL,
	[SERVICIO] [varchar](50) NULL,
	[TIPO_DOCUMENTO] [varchar](50) NULL,
	[NPS] [varchar](40) NULL,
	[ID_UNIDAD] [int] NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[TMP_ESTUDIANTES_CEDESARROLLO](
	[TIPO_DOCUMENTO] [nvarchar](255) NULL,
	[DOCUMENTO_ESTUDIANTE] [nvarchar](255) NULL,
	[NOMBRE_ESTUDIANTE] [nvarchar](255) NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[TMP_LISTADO_MATRICULAS_Q10](
	[JORNADA] [nvarchar](255) NULL,
	[NOMBRE_ESTUDIANTE] [nvarchar](255) NULL,
	[TIPO_DOCUMENTO] [nvarchar](255) NULL,
	[DOCUMENTO_ESTUDIANTE] [nvarchar](255) NULL,
	[FECHA_MATRICULA] [datetime] NULL,
	[TELEFONO] [nvarchar](255) NULL,
	[CELULAR] [nvarchar](255) NULL,
	[CORREO] [nvarchar](255) NULL,
	[SEMESTRE] [nvarchar](255) NULL,
	[ESTADO] [nvarchar](255) NULL,
	[SEDE] [nvarchar](255) NULL,
	[PROGRAMA] [nvarchar](255) NULL,
	[ID_UNIDAD] [int] NULL
) ON [PRIMARY]
GO
CREATE TABLE [Transversal].[TMP_MATRICULAS_CEDESARROLLO](
	[NOMBRE_ESTUDIANTE] [nvarchar](200) NULL,
	[TIPO_DOCUMENTO] [nvarchar](255) NULL,
	[DOCUMENTO_ESTUDIANTE] [nvarchar](255) NULL,
	[FECHA_MATRICULA] [datetime] NULL,
	[TELEFONO] [nvarchar](40) NULL,
	[CELULAR] [nvarchar](40) NULL,
	[CORREO] [nvarchar](200) NULL,
	[SEMESTRE] [nvarchar](40) NULL,
	[ESTADO] [nvarchar](255) NULL,
	[SEDE] [nvarchar](255) NULL,
	[PROGRAMA] [nvarchar](255) NULL,
	[ID_UNIDAD] [int] NULL,
	[DOCUMENTOS_COMPLETOS] [nvarchar](2) NULL,
	[JORNADA] [nvarchar](255) NULL,
	[ID_JORNADA] [int] NULL,
	[ID_PROGRAMA] [int] NULL,
	[FECHA_INICIO_PERIODO] [date] NULL
) ON [PRIMARY]
GO
CREATE TABLE [Transversal].[TMP_POBLACION_EDUCACION](
	[TIPO_DOCUMENTO_SIGLAS] [nvarchar](3) NULL,
	[DOCUMENTO] [nvarchar](20) NULL,
	[ID_TIPO_DOCUMENTO] [nvarchar](4) NULL
) ON [PRIMARY]
GO
CREATE TABLE [Transversal].[TMP_PROCESO_MATRICULA_COLEGIO](
	[ID_FECHA] [int] NULL,
	[ID_ANIO_ACADEMICO] [nvarchar](4) NULL,
	[BP] [nvarchar](20) NULL,
	[ID_CATEGORIA] [int] NULL,
	[ID_CURSO] [int] NULL,
	[ID_TIPO_ESTUDIANTE] [int] NULL,
	[IND_CODEUDOR] [int] NULL,
	[P_CODEUDOR] [int] NULL,
	[T_CODEUDOR] [int] NULL,
	[IND_SECRETARIA_ACADEMICA] [int] NULL,
	[P_SECRETARIA_ACADEMICA] [int] NULL,
	[T_SECRETARIA_ACADEMICA] [int] NULL,
	[IND_PSICOLOGIA] [int] NULL,
	[P_PSICOLOGIA] [int] NULL,
	[T_PSICOLOGIA] [int] NULL,
	[IND_COORDINACION_ACADEMICA] [int] NULL,
	[P_COORDINACION_ACADEMICA] [int] NULL,
	[T_COORDINACION_ACADEMICA] [int] NULL,
	[INDICADOR] [int] NULL,
	[T_TOTAL_GESTION] [int] NULL,
	[IND_CUMPLIMIENTO] [int] NULL,
	[IND_EN_PROCESO] [int] NULL,
	[IND_ADMITIDO] [int] NULL,
	[IND_NO_ADMITIDO] [int] NULL,
	[IND_DESISTIDO] [int] NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[STG_FACT_AFILIACIONES] (
    [ACTIVIDAD] NVARCHAR(255),
    [ADEUDA] DECIMAL(18, 2) NULL,
    [ANIO_ACADEMICO] INT NULL,
    [CANTIDAD_MATERIAL] INT NULL,
    [CALIFICACION] NVARCHAR(255) NULL,
    [CAUSA] NVARCHAR(255) NULL,
    [CATEGORIA_VENTA] NVARCHAR(255) NULL,
    [COSTO] DECIMAL(18, 2) NULL,
    [CURSO] NVARCHAR(255) NULL,
    [DESCRIPCION] NVARCHAR(255) NULL,
    [ESTADO] NVARCHAR(255) NULL,
    [ESTADOREGISTRO] NVARCHAR(50),
    [ESTADO_PAGO] NVARCHAR(255) NULL,
    [ESTRATO] INT NULL,
	[DISCAPACIDAD] NVARCHAR (10) NULL,
	[EDAD] INT NULL,
	[FECHA_NACIMIENTO] DATETIME NULL,
    [FECHA_AFILIACION] DATE NULL,
    [FECHA_MENSUAL] DATE,
    [FECHA_RETIRO] DATE NULL,
    [FECHA_ADMISION] DATE NULL,
    [ID_AFILIADO] INT NULL,
    [ID_CATEGORIA] INT NULL,
    [ID_CIUDAD] INT NULL,
    [ID_CONCEPTO] INT NULL,
    [ID_CURSO] INT NULL,
    [ID_EMPRESA] INT NULL,
    [ID_ESTADO_CIVIL] INT NULL,
    [ID_ESTADO_GESTION] INT NULL,
    [ID_FACTOR_VULNERABILIDAD] INT NULL,
    [ID_FECHA] INT,
    [ID_GENERO] INT NULL,
    [ID_GRADO] INT NULL,
    [ID_MATERIAL] INT NULL,
    [ID_PERTENENCIA_ETNICA] INT NULL,
    [ID_POBLACION] INT NULL,
    [ID_PROGRAMA] INT NULL,
    [ID_PREGUNTA] INT NULL,
    [ID_TIPO_AFILIADO] INT NULL,
    [ID_UNIDAD] INT NULL,
    [NO_PRESTAMOS] INT NULL,
    [NUMERO_APORTES] INT,
    [PARTNER] NVARCHAR(50),
    [PARTNER_AFILIADO] NVARCHAR(50) NULL,
    [PARTNER_EMPRESA] NVARCHAR(50) NULL,
    [RESPUESTA] NVARCHAR(255) NULL,
    [SALARIO_BASICO] DECIMAL(18, 2) NULL,
    [SERVICIO_TRANSPORTE] NVARCHAR(255) NULL,
    [SUBSIDIO] DECIMAL(20, 2) NULL,
    [TIPO_AFILIADO] NVARCHAR(255) NULL,
    [TIPO_POBLACION] NVARCHAR(50),
    [TOTAL_APORTES] DECIMAL(18, 2),
    [VALOR_FACTURADO] DECIMAL(18, 2) NULL,
    [VALOR_MATERIAL] DECIMAL(18, 2) NULL,
    [VALOR_PAGADO] DECIMAL(18, 2) NULL,
    [VALOR_PAGADO_SIN_IMP] DECIMAL(18, 2) NULL,
	[FUENTE_PRINCIPAL] NVARCHAR(250) NULL,
	[ID_PQR] [nvarchar](40) NULL DEFAULT -1,
	[ESTADO_PQR] [nvarchar](40),
	[ID_BENEFICIARIO] [int] NULL DEFAULT -1,
	[CAUSA_PQR] [nvarchar](40),
	[TIPO_PQRS] [nvarchar](40),
	[ID_TARIFA] [int] NULL DEFAULT -1
)
GO

CREATE TABLE [Transversal].[STG_PLAN_COBERTURA_ADULTO_DISCAPACIDAD](
	[ANIO] [nvarchar](255) NULL,
	[COD_INFRAESTRUCTURA_CCF] [nvarchar](255) NULL,
	[SERVICIO] [float] NULL,
	[CATEGORIA_CCF] [float] NULL,
	[NUM_PERSONAS_COBERTURA_SERVICIOS] [float] NULL,
	[MES_PROYECTADO] [float] NULL
) ON [PRIMARY]
GO

CREATE TABLE [Transversal].[TMP_DESERTORES_DESARROLLO](
	[PROGRAMA] [nvarchar](255) NULL,
	[NOMBRE_ESTUDIANTE] [nvarchar](255) NULL,
	[GRUPO] [nvarchar](255) NULL,
	[MODULO] [nvarchar](255) NULL,
	[SEMESTRE] [nvarchar](255) NULL,
	[CREDITOS] [float] NULL,
	[PORCENTAJE _INASISTENCIA] [float] NULL,
	[SEDE] [nvarchar](255) NULL,
	[JORNADA] [nvarchar](255) NULL,
	[TIPO_DOCUMENTO] [nvarchar](255) NULL,
	[DOCUMENTO_ESTUDIANTE] [float] NULL,
	[FECHA] [datetime] NULL
) ON [PRIMARY]
GO